import { db } from './firebase.js';
import { doc,getDoc,setDoc,serverTimestamp,collection,getDocs,updateDoc,increment } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
const names=['BRONZE','SILVER','GOLD','PREMIUM','PLATINUM','SELECT','BLACK','ELITE','PRIME','FOUNDER'];
const level=document.getElementById('adminLevel'),field=document.getElementById('adminBenefits'),status=document.getElementById('adminStatus');
async function loadBenefits(){const s=await getDoc(doc(db,'niveis',level.value));field.value=s.exists()&&Array.isArray(s.data().beneficios)?s.data().beneficios.join('\n'):'';status.textContent=''}
async function saveBenefits(){const beneficios=field.value.split('\n').map(x=>x.trim()).filter(Boolean);await setDoc(doc(db,'niveis',level.value),{beneficios,atualizadoEm:serverTimestamp()},{merge:true});status.textContent='Benefícios salvos com sucesso.'}
level.addEventListener('change',loadBenefits);document.getElementById('saveBenefits').addEventListener('click',saveBenefits);loadBenefits();
const offerId=document.getElementById('offerId'),offerStatus=document.getElementById('offerStatus');
async function loadOffer(){const s=await getDoc(doc(db,'ofertas',offerId.value));const d=s.exists()?s.data():{};offerCategory.value=d.categoria||'';offerTitle.value=d.titulo||'';offerDescription.value=d.descricao||'';offerButton.value=d.botao||'';offerOrder.value=d.ordem||Number(offerId.value.replace('oferta',''))||1;offerStatus.textContent=''}
async function saveOffer(){const data={categoria:offerCategory.value.trim(),titulo:offerTitle.value.trim(),descricao:offerDescription.value.trim(),botao:offerButton.value.trim()||'Ver benefício',ordem:Number(offerOrder.value)||1,ativo:true,atualizadoEm:serverTimestamp()};if(!data.titulo)return offerStatus.textContent='Informe o título da oferta.';await setDoc(doc(db,'ofertas',offerId.value),data,{merge:true});offerStatus.textContent='Oferta salva com sucesso.'}
offerId.addEventListener('change',loadOffer);document.getElementById('saveOffer').addEventListener('click',saveOffer);loadOffer();
const clientSelect=document.getElementById('clientSelect'),clientSummary=document.getElementById('clientSummary'),purchaseStatus=document.getElementById('purchaseStatus');let clients=[];
function renderClient(){const c=clients.find(x=>x.id===clientSelect.value);if(!c){clientSummary.innerHTML='<strong>Nenhum cliente selecionado</strong><span>O nível e o telefone aparecerão aqui.</span>';return}const vip=Math.max(0,Math.min(9,Number(c.vip)||0));clientSummary.innerHTML=`<strong>${c.nome||c.email||'Cliente'}</strong><span>LV${vip+1} — ${names[vip]} · ${c.telefone||'Telefone não informado'}</span>`}
async function loadClients(){try{const snap=await getDocs(collection(db,'usuarios'));clients=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.nome||'').localeCompare(b.nome||''));clientSelect.innerHTML=clients.map(c=>`<option value="${c.id}">${c.nome||c.email||'Cliente'} — LV${Math.max(1,(Number(c.vip)||0)+1)}</option>`).join('')||'<option value="">Nenhum cliente encontrado</option>';renderClient()}catch(e){clientSelect.innerHTML='<option value="">Sem permissão para listar clientes</option>';purchaseStatus.textContent='As regras do Firestore precisam permitir que administradores leiam a coleção usuarios.'}}
async function savePurchase(){const c=clients.find(x=>x.id===clientSelect.value);if(!c)return purchaseStatus.textContent='Selecione um cliente.';const raw=document.getElementById('purchaseValue').value.trim();const value=Number(raw.replace('R$','').replace(/\./g,'').replace(',','.'));if(!Number.isFinite(value)||value<=0)return purchaseStatus.textContent='Informe um valor válido.';const gained=Math.floor(value/100);if(gained<1)return purchaseStatus.textContent='A compra precisa atingir R$ 100 para gerar carimbo.';let vip=Number(c.vip)||0,stamps=(Number(c.carimbos)||0)+gained;while(stamps>=10&&vip<9){stamps-=10;vip++}if(vip===9)stamps=Math.min(stamps,10);await updateDoc(doc(db,'usuarios',c.id),{vip,carimbos:stamps,creditos:increment(value),atualizadoEm:serverTimestamp()});c.vip=vip;c.carimbos=stamps;c.creditos=Number(c.creditos||0)+value;renderClient();document.getElementById('purchaseValue').value='';purchaseStatus.textContent=`Compra registrada para ${c.nome||c.email}. ${gained} carimbo(s) adicionado(s).`}
clientSelect.addEventListener('change',renderClient);document.getElementById('savePurchase').addEventListener('click',savePurchase);loadClients();