import { auth,db } from './firebase.js';
import { doc,getDoc,setDoc,serverTimestamp,collection,getDocs,updateDoc,addDoc } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
import { money,calcularCarteira } from './regras-fidelidade.js';
const LEVELS=['MEMBRO','BRONZE','SILVER','GOLD','PREMIUM','PLATINUM','SELECT','BLACK','ELITE','PRIME','FOUNDER'];
const $=id=>document.getElementById(id),parseMoney=raw=>Number(String(raw||'').replace('R$','').replace(/\./g,'').replace(',','.').trim()),shortUid=uid=>String(uid||'').slice(-6),normal=v=>String(v||'').trim().toLowerCase();
const roleLabel=role=>['admin','administrador','master'].includes(normal(role))?'ADMIN':'CLIENTE';
const audit=(tipo,payload)=>addDoc(collection(db,'logs'),{tipo,...payload,admin:{uid:auth.currentUser?.uid||'',email:auth.currentUser?.email||''},criadoEm:serverTimestamp()});
const level=$('adminLevel'),field=$('adminBenefits'),status=$('adminStatus'),correctionClient=$('correctionClient'),correctionVip=$('correctionVip'),correctionStamps=$('correctionStamps'),correctionCredits=$('correctionCredits'),correctionReason=$('correctionReason'),correctionStatus=$('correctionStatus'),duplicateInfo=$('duplicateInfo'),offerId=$('offerId'),offerStatus=$('offerStatus');
let clients=[];
async function loadBenefits(){const s=await getDoc(doc(db,'niveis',level.value));field.value=s.exists()&&Array.isArray(s.data().beneficios)?s.data().beneficios.join('\n'):'';status.textContent=''}
async function saveBenefits(){try{await setDoc(doc(db,'niveis',level.value),{beneficios:field.value.split('\n').map(x=>x.trim()).filter(Boolean),atualizadoEm:serverTimestamp()},{merge:true});status.textContent='Benefícios salvos.'}catch(e){console.error(e);status.textContent='Não foi possível salvar.'}}
async function loadOffer(){const s=await getDoc(doc(db,'ofertas',offerId.value)),d=s.exists()?s.data():{};$('offerCategory').value=d.categoria||'';$('offerTitle').value=d.titulo||'';$('offerDescription').value=d.descricao||'';$('offerButton').value=d.botao||'';$('offerOrder').value=d.ordem||Number(offerId.value.replace('oferta',''))||1;offerStatus.textContent=''}
async function saveOffer(){const data={categoria:$('offerCategory').value.trim(),titulo:$('offerTitle').value.trim(),descricao:$('offerDescription').value.trim(),botao:$('offerButton').value.trim()||'Ver benefício',ordem:Number($('offerOrder').value)||1,ativo:true,atualizadoEm:serverTimestamp()};if(!data.titulo)return offerStatus.textContent='Informe o título.';try{await setDoc(doc(db,'ofertas',offerId.value),data,{merge:true});offerStatus.textContent='Oferta salva.'}catch(e){console.error(e);offerStatus.textContent='Não foi possível salvar.'}}
function optionLabel(c){const you=c.id===auth.currentUser?.uid?' · VOCÊ':'';return `${c.nome||c.email||'Cliente'} — LV${Math.max(0,Math.min(10,Number(c.vip)||0))} · ${roleLabel(c.role)} · ${c.email||'sem e-mail'} · ID ${shortUid(c.id)}${you}`}
function renderCorrection(){const c=clients.find(x=>x.id===correctionClient.value);if(!c){duplicateInfo.innerHTML='<span>Selecione um cliente.</span>';return}const vip=Math.max(0,Math.min(10,Number(c.vip)||0));correctionVip.value=String(vip);correctionStamps.value=String(Math.max(0,Math.min(10,Number(c.carimbos)||0)));correctionCredits.value=Number(c.creditos||0).toFixed(2).replace('.',',');duplicateInfo.innerHTML=`<strong>${c.nome||c.email||'Cliente'}</strong><span>${c.email||'Sem e-mail'} · ${roleLabel(c.role)} · ID ${shortUid(c.id)}</span><span>LV${vip} ${LEVELS[vip]} · Total ${money(c.totalGasto||0)} · Bônus ${money(c.creditos||0)}</span>`}
async function loadClients(){try{const selected=correctionClient.value,snap=await getDocs(collection(db,'usuarios'));clients=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.nome||a.email||'').localeCompare(b.nome||b.email||''));correctionClient.innerHTML='<option value="">Selecione um cliente</option>'+clients.map(c=>`<option value="${c.id}">${optionLabel(c)}</option>`).join('');const requested=new URLSearchParams(location.search).get('cliente');if(clients.some(c=>c.id===requested))correctionClient.value=requested;else if(clients.some(c=>c.id===selected))correctionClient.value=selected;else if(clients.some(c=>c.id===auth.currentUser?.uid))correctionClient.value=auth.currentUser.uid;renderCorrection()}catch(e){console.error(e);correctionStatus.textContent='Sem permissão para listar clientes.'}}
async function saveCorrection(){const c=clients.find(x=>x.id===correctionClient.value);if(!c)return correctionStatus.textContent='Selecione um cliente.';const vip=Math.max(0,Math.min(10,Number(correctionVip.value)||0)),carimbos=Math.max(0,Math.min(10,Number(correctionStamps.value)||0)),creditos=parseMoney(correctionCredits.value),motivo=correctionReason.value.trim();if(!Number.isFinite(creditos)||creditos<0)return correctionStatus.textContent='Informe um bônus válido.';if(motivo.length<3)return correctionStatus.textContent='Informe o motivo.';try{const carteira=calcularCarteira(c,vip),bonusManual=Math.max(0,creditos-carteira.bonusNivel);await updateDoc(doc(db,'usuarios',c.id),{vip,carimbos,bonusBaseVip:carteira.bonusBaseVip,bonusNivel:carteira.bonusNivel,bonusManual,creditos,atualizadoEm:serverTimestamp()});await audit('conta_corrigida',{clienteId:c.id,motivo,depois:{vip,carimbos,creditos,bonusManual,bonusNivel:carteira.bonusNivel}});correctionStatus.textContent='Conta atualizada.';correctionReason.value='';await loadClients()}catch(e){console.error(e);correctionStatus.textContent='Não foi possível atualizar.'}}
async function resetCustomer(){const c=clients.find(x=>x.id===correctionClient.value),motivo=correctionReason.value.trim();if(!c)return correctionStatus.textContent='Selecione um cliente.';if(motivo.length<3)return correctionStatus.textContent='Informe o motivo.';if(!confirm(`Zerar progresso e bônus de ${c.nome||c.email}?`))return;try{await updateDoc(doc(db,'usuarios',c.id),{vip:0,carimbos:0,totalGasto:0,bonusBaseVip:0,bonusNivel:0,bonusManual:0,creditos:0,atualizadoEm:serverTimestamp()});await audit('conta_zerada',{clienteId:c.id,motivo});correctionStatus.textContent='Conta zerada.';correctionReason.value='';await loadClients()}catch(e){console.error(e);correctionStatus.textContent='Não foi possível zerar.'}}
level.addEventListener('change',loadBenefits);$('saveBenefits').addEventListener('click',saveBenefits);offerId.addEventListener('change',loadOffer);$('saveOffer').addEventListener('click',saveOffer);correctionClient.addEventListener('change',renderCorrection);$('saveCorrection').addEventListener('click',saveCorrection);$('resetCustomer').addEventListener('click',resetCustomer);loadBenefits();loadOffer();loadClients();