import { auth, db } from './firebase.js';
import { onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import { doc, getDoc } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';

const BUILD='20260731-1025';
function carregarCss(href){if(document.querySelector(`link[href^="${href}"]`))return;const style=document.createElement('link');style.rel='stylesheet';style.href=`${href}?v=${BUILD}`;document.head.append(style)}
carregarCss('shell-fixes.css');carregarCss('dark-mode.css');carregarCss('ui-fixes-v2.css');
function temaValido(value){return value==='dark'||value==='light'}
function aplicarTema(tema,uid=''){const valor=tema==='dark'?'dark':'light';document.documentElement.dataset.theme=valor;localStorage.setItem('wd-theme',valor);if(uid)localStorage.setItem(`wd-theme:${uid}`,valor);document.dispatchEvent(new CustomEvent('wd-theme-ready',{detail:{theme:valor,uid}}))}
window.aplicarTemaWD=(tema,uid='')=>aplicarTema(tema,uid||auth.currentUser?.uid||'');
const temaInicial=localStorage.getItem('wd-theme');if(temaValido(temaInicial))aplicarTema(temaInicial);
const body=document.body,menu=document.querySelector('.menu');
let scrollTravado=0;
if(body.dataset.adminPage==='true'&&!document.getElementById('deleteDuplicateProfile')){const b=document.createElement('button');b.id='deleteDuplicateProfile';b.type='button';b.hidden=true;document.body.append(b)}
function travarPagina(){scrollTravado=window.scrollY||0;body.style.position='fixed';body.style.top=`-${scrollTravado}px`;body.style.left='0';body.style.right='0';body.style.width='100%'}
function destravarPagina(){body.style.position='';body.style.top='';body.style.left='';body.style.right='';body.style.width='';window.scrollTo(0,scrollTravado)}
function fecharMenu(){const estavaAberto=body.classList.contains('menu-open');body.classList.remove('menu-open');document.querySelector('.mobile-menu-trigger')?.setAttribute('aria-expanded','false');if(estavaAberto)destravarPagina()}
function abrirMenu(){if(body.classList.contains('menu-open'))return;travarPagina();body.classList.add('menu-open');document.querySelector('.mobile-menu-trigger')?.setAttribute('aria-expanded','true')}
function montarMenuMobile(){if(!menu||document.querySelector('.mobile-menu-trigger'))return;const trigger=document.createElement('button');trigger.className='mobile-menu-trigger';trigger.type='button';trigger.setAttribute('aria-label','Abrir menu');trigger.setAttribute('aria-expanded','false');trigger.innerHTML='<span></span><span></span><span></span>';const backdrop=document.createElement('button');backdrop.className='menu-backdrop';backdrop.type='button';backdrop.setAttribute('aria-label','Fechar menu');const close=document.createElement('button');close.className='menu-close';close.type='button';close.setAttribute('aria-label','Fechar menu');close.textContent='×';menu.prepend(close);trigger.addEventListener('click',()=>body.classList.contains('menu-open')?fecharMenu():abrirMenu());close.addEventListener('click',fecharMenu);backdrop.addEventListener('click',fecharMenu);menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',fecharMenu));(document.querySelector('.conteudo')||document.body).prepend(trigger);document.body.append(backdrop);window.addEventListener('pageshow',fecharMenu);window.addEventListener('resize',()=>{if(innerWidth>768)fecharMenu()});document.addEventListener('keydown',event=>{if(event.key==='Escape')fecharMenu()})}
function garantirLinksAdmin(){if(!menu)return;const logout=menu.querySelector('.logout-btn, button[onclick], [data-action="logout"]');const current=location.pathname.split('/').pop()||'home.html';const defs=[{href:'registrar-compra.html',text:'Registrar compra'},{href:'historico-vendas.html',text:'Histórico de vendas'},{href:'estoque.html',text:'Estoque & Produtos'},{href:'desempenho.html',text:'Desempenho'},{href:'perfil-admin.html',text:'Administração'},{href:'excluir-cliente.html',text:'Excluir conta'}];const fragment=document.createDocumentFragment();defs.forEach(def=>{const matches=[...menu.querySelectorAll('a')].filter(a=>a.getAttribute('href')===def.href);matches.slice(1).forEach(a=>a.remove());const link=matches[0]||document.createElement('a');link.href=def.href;link.textContent=def.text;link.dataset.adminLink='true';link.classList.add('admin-only');link.classList.toggle('ativo',current===def.href);fragment.append(link)});menu.insertBefore(fragment,logout||null)}
async function carregarDocumentoUsuario(user){const snap=await getDoc(doc(db,'usuarios',user.uid));if(snap.exists())return snap.data();const error=new Error('Cadastro do clube não encontrado.');error.code='wd/missing-club-profile';throw error}
async function sair(event){event?.preventDefault?.();event?.stopPropagation?.();document.querySelectorAll('.logout-btn,[data-action="logout"]').forEach(botao=>{botao.disabled=true;botao.textContent='Saindo...'});try{body.classList.add('is-signing-out');await signOut(auth)}catch(error){console.error('Erro ao sair:',error)}finally{sessionStorage.clear();localStorage.removeItem('firebase:previous_websocket_failure');location.replace('index.html')}}
window.sair=sair;
function ligarLogout(){document.querySelectorAll('.logout-btn,.menu button[onclick*="sair"],[data-action="logout"]').forEach(botao=>{botao.removeAttribute('onclick');botao.type='button';botao.dataset.action='logout';botao.onclick=null;botao.addEventListener('click',sair,{capture:true})})}
garantirLinksAdmin();montarMenuMobile();ligarLogout();
onAuthStateChanged(auth,async user=>{if(!user){location.replace('index.html');return}const chave=`wd-theme:${user.uid}`,temaUsuario=localStorage.getItem(chave);if(temaValido(temaUsuario))aplicarTema(temaUsuario,user.uid);let dados;try{dados=await carregarDocumentoUsuario(user)}catch(error){console.error('Perfil do clube indisponível:',error);if(error.code==='wd/missing-club-profile'){alert('Esta conta não possui mais cadastro ativo no WD Founder.');await signOut(auth).catch(()=>{});location.replace('index.html')}return}const temaRemoto=temaValido(dados?.tema)?dados.tema:null;if(temaRemoto)aplicarTema(temaRemoto,user.uid);else if(temaValido(temaUsuario))aplicarTema(temaUsuario,user.uid);else aplicarTema('light',user.uid);const role=String(dados?.role||'cliente').toLowerCase(),admin=['admin','administrador','master'].includes(role);document.querySelectorAll('.admin-only').forEach(el=>el.classList.toggle('is-visible',admin));document.documentElement.dataset.role=admin?'admin':'cliente';if(body.dataset.adminPage==='true'&&!admin){location.replace('home.html');return}document.dispatchEvent(new CustomEvent('wd-role-ready',{detail:{user,role,admin,dados}}))});