import { auth, db } from './firebase.js';
import { onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import { doc, getDoc, updateDoc, increment } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
const levels=['BRONZE','SILVER','GOLD','PREMIUM','PLATINUM','SELECT','BLACK','ELITE','PRIME','FOUNDER'];
const colors=[['#c67a2d','#6f3312','#271005'],['#dedede','#8d8d8d','#404040'],['#e2bf49','#94710e','#3b2a00'],['#8d62ef','#4a24a4','#1d0c4b'],['#f4f5f6','#aeb3b8','#555d65'],['#2471e8','#093b89','#031b46'],['#353535','#111','#000'],['#d14455','#7c1120','#2d040a'],['#3256b8','#172e73','#071337'],['#d8ad45','#89600f','#2b1a00']];
let currentUser=null,currentData={vip:0,carimbos:0,creditos:0,nome:'Cliente Founder'},isAdmin=false;
function paint(){const vip=Math.max(0,Math.min(9,Number(currentData.vip)||0));const stamps=Math.max(0,Math.min(10,Number(currentData.carimbos)||0));const c=colors[vip];const card=document.getElementById('cartao');card.style.background=`linear-gradient(135deg,${c[0]},${c[1]} 58%,${c[2]})`;document.getElementById('nivel').textContent=`LV${vip+1}`;document.getElementById('membroNivel').textContent=`MEMBRO ${levels[vip]}`;document.getElementById('seloNivel').textContent=levels[vip];document.getElementById('clienteNome').textContent=currentData.nome||'Cliente Founder';document.getElementById('creditosCliente').textContent=Number(currentData.creditos||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});document.getElementById('textoCarimbo').textContent=`${stamps} / 10 carimbos`;document.getElementById('listaCarimbos').innerHTML=Array.from({length:10},(_,i)=>`<span class="stamp ${i<stamps?'on':''}"></span>`).join('');document.getElementById('progressBar').style.width=`${stamps*10}%`;loadNext(vip,stamps)}
async function loadNext(vip,stamps){const next=Math.min(9,vip+1);document.getElementById('nextLevel').textContent=vip===9?'Nível máximo':`LV${next+1} — ${levels[next]}`;document.getElementById('missing').textContent=vip===9?'Você chegou ao Founder':`Faltam ${Math.max(0,10-stamps)} carimbos`;let benefits=['Benefícios exclusivos do próximo nível','Condições especiais para membros'];try{const s=await getDoc(doc(db,'niveis',`lv${next+1}`));if(s.exists()&&Array.isArray(s.data().beneficios)) benefits=s.data().beneficios.filter(Boolean)}catch(e){}document.getElementById('benefits').innerHTML=benefits.length?benefits.map(x=>`<div class="benefit-row">${x}</div>`).join(''):'<div class="empty-benefits">Benefícios serão publicados em breve.</div>'}
async function registerPurchase(){if(!isAdmin||!currentUser)return;const raw=prompt('Valor da compra:');if(raw===null)return;const value=Number(raw.replace('R$','').replace('.','').replace(',','.').trim());if(!Number.isFinite(value)||value<=0)return alert('Valor inválido.');const gained=Math.floor(value/100);if(!gained)return alert('A compra precisa atingir R$ 100 para gerar carimbo.');let vip=Number(currentData.vip)||0,stamps=(Number(currentData.carimbos)||0)+gained;while(stamps>=10&&vip<9){stamps-=10;vip++}await updateDoc(doc(db,'usuarios',currentUser.uid),{vip,carimbos:stamps,creditos:increment(value)});currentData={...currentData,vip,carimbos:stamps,creditos:Number(currentData.creditos||0)+value};paint();alert('Compra registrada com sucesso.')}window.registrarCompra=registerPurchase;
document.addEventListener('wd-role-ready',e=>{isAdmin=e.detail.admin;document.querySelector('.admin-purchase')?.classList.toggle('is-visible',isAdmin)});
onAuthStateChanged(auth,async user=>{if(!user)return;currentUser=user;const s=await getDoc(doc(db,'usuarios',user.uid));if(s.exists())currentData={...currentData,...s.data()};paint()});