import { db } from './firebase.js';
import { collection,getDocs } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
import { money } from './regras-fidelidade.js';
const $=id=>document.getElementById(id);
let products=[];
const num=value=>Math.max(0,Number(value)||0);
const margin=(cost,price)=>price>0?((price-cost)/price)*100:0;
const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function renderKpis(){const active=products.filter(p=>p.ativo!==false),units=active.reduce((s,p)=>s+num(p.estoque),0),investment=active.reduce((s,p)=>s+num(p.estoque)*num(p.precoCusto),0),potential=active.reduce((s,p)=>s+num(p.estoque)*num(p.preco),0),profit=potential-investment,low=active.filter(p=>num(p.estoque)>0&&num(p.estoque)<=num(p.estoqueMinimo||3)).length,out=active.filter(p=>num(p.estoque)===0).length,weightedPrice=active.reduce((s,p)=>s+num(p.preco)*num(p.estoque),0),weightedProfit=active.reduce((s,p)=>s+(num(p.preco)-num(p.precoCusto))*num(p.estoque),0),avg=weightedPrice>0?weightedProfit/weightedPrice*100:0;$('stockValue').textContent=money(investment);$('potentialRevenue').textContent=money(potential);$('expectedProfit').textContent=money(profit);$('stockUnits').textContent=String(units);$('productCount').textContent=String(active.length);$('lowStock').textContent=String(low);$('outOfStock').textContent=String(out);$('averageMargin').textContent=`${avg.toFixed(1).replace('.',',')}%`}
function renderProducts(){const sorted=[...products].filter(p=>p.ativo!==false).sort((a,b)=>num(b.estoque)*num(b.precoCusto)-num(a.estoque)*num(a.precoCusto));$('productsList').innerHTML=sorted.length?sorted.map(p=>{const stock=num(p.estoque),cost=num(p.precoCusto),price=num(p.preco),investment=stock*cost,potential=stock*price,profit=potential-investment,low=stock===0?'Esgotado':stock<=num(p.estoqueMinimo||3)?'Estoque baixo':`${stock} peças`;return `<article class="product-card"><div class="product-top"><div><h3>${esc(p.nome||'Produto sem nome')}</h3><p>${esc(p.categoria||'Sem categoria')} · ${esc(p.selo||'Produto')}</p></div><span class="stock-badge ${stock<=num(p.estoqueMinimo||3)?'low':''}">${low}</span></div><div class="product-metrics"><div><span>Investido</span><strong>${money(investment)}</strong></div><div><span>Venda potencial</span><strong>${money(potential)}</strong></div><div><span>Lucro esperado</span><strong>${money(profit)}</strong></div><div><span>Margem</span><strong>${margin(cost,price).toFixed(1).replace('.',',')}%</strong></div></div></article>`}).join(''):'<div class="empty-products">Nenhuma mercadoria publicada.</div>'}
function ranking(target,list,empty){$(target).innerHTML=list.length?list.map((item,index)=>`<div class="ranking-item"><div><strong>${index+1}. ${esc(item.nome)}</strong><small>${esc(item.detalhe)}</small></div><strong>${money(item.valor)}</strong></div>`).join(''):`<div class="empty-products">${empty}</div>`}
function renderRankings(){const active=products.filter(p=>p.ativo!==false);ranking('topInvestment',[...active].map(p=>({nome:p.nome||'Produto',valor:num(p.estoque)*num(p.precoCusto),detalhe:`${num(p.estoque)} peça(s)`})).sort((a,b)=>b.valor-a.valor).slice(0,6),'Sem investimento cadastrado.');ranking('topProfit',[...active].map(p=>({nome:p.nome||'Produto',valor:(num(p.preco)-num(p.precoCusto))*num(p.estoque),detalhe:`Margem ${margin(num(p.precoCusto),num(p.preco)).toFixed(1).replace('.',',')}%`})).sort((a,b)=>b.valor-a.valor).slice(0,6),'Sem lucro calculado.');const cats=new Map();active.forEach(p=>{const key=p.categoria||'Sem categoria',current=cats.get(key)||{nome:key,valor:0,unidades:0};current.valor+=num(p.estoque)*num(p.preco);current.unidades+=num(p.estoque);cats.set(key,current)});ranking('topCategories',[...cats.values()].map(x=>({nome:x.nome,valor:x.valor,detalhe:`${x.unidades} peça(s)`})).sort((a,b)=>b.valor-a.valor).slice(0,6),'Sem categorias cadastradas.')}
async function load(){const snap=await getDocs(collection(db,'ofertas'));products=snap.docs.map(d=>({id:d.id,...d.data()})).filter(p=>p.tipo==='produto');renderKpis();renderProducts();renderRankings()}
load().catch(error=>{console.error(error);$('productsList').innerHTML='<div class="empty-products">Não foi possível carregar o dashboard. Verifique as regras do Firestore.</div>'});