import { auth,db } from './firebase.js';
import { collection,getDocs,doc,setDoc,updateDoc,addDoc,serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
import { money } from './regras-fidelidade.js';
const $=id=>document.getElementById(id);
let products=[],purchases=[];
const parseMoney=raw=>Number(String(raw||'').replace('R$','').replace(/\./g,'').replace(',','.').trim());
const monthStart=()=>new Date(new Date().getFullYear(),new Date().getMonth(),1);
const dateOf=v=>{try{return v?.toDate?v.toDate():new Date(v)}catch{return null}};
function margin(cost,price){return price>0?((price-cost)/price)*100:0}
function updatePreview(){const cost=Math.max(0,parseMoney($('productCost').value)||0),price=Math.max(0,parseMoney($('productPrice').value)||0);$('marginPreview').textContent=`${margin(cost,price).toFixed(1).replace('.',',')}%`;$('profitPreview').textContent=`Lucro unitário: ${money(price-cost)}`}
function resetForm(){ $('productForm').reset();$('productId').value='';$('productStock').value='0';$('productMinimum').value='3';$('formTitle').textContent='Nova peça';$('cancelEdit').hidden=true;$('productStatus').textContent='';updatePreview() }
function editProduct(id){const p=products.find(x=>x.id===id);if(!p)return;$('productId').value=p.id;$('productName').value=p.nome||'';$('productCategory').value=p.categoria||'Outro';$('productSku').value=p.sku||'';$('productCost').value=Number(p.precoCusto||0).toFixed(2).replace('.',',');$('productPrice').value=Number(p.precoVenda||0).toFixed(2).replace('.',',');$('productStock').value=Number(p.estoque)||0;$('productMinimum').value=Number(p.estoqueMinimo)||0;$('formTitle').textContent='Editar peça';$('cancelEdit').hidden=false;updatePreview();scrollTo({top:0,behavior:'smooth'})}
async function toggleProduct(id){const p=products.find(x=>x.id===id);if(!p)return;await updateDoc(doc(db,'produtos',id),{ativo:p.ativo===false,true:false,atualizadoEm:serverTimestamp()});await addDoc(collection(db,'logs'),{tipo:'produto_status_alterado',produtoId:id,ativo:p.ativo===false,admin:{uid:auth.currentUser?.uid||'',email:auth.currentUser?.email||''},criadoEm:serverTimestamp()});await load()}
function renderProducts(){const q=$('productSearch').value.trim().toLowerCase(),list=products.filter(p=>!q||`${p.nome||''} ${p.categoria||''} ${p.sku||''}`.toLowerCase().includes(q));$('productsList').innerHTML=list.length?list.map(p=>{const stock=Math.max(0,Number(p.estoque)||0),minimum=Math.max(0,Number(p.estoqueMinimo)||0),cost=Math.max(0,Number(p.precoCusto)||0),price=Math.max(0,Number(p.precoVenda)||0),low=stock<=minimum;return `<article class="product-card"><div class="product-top"><div><h3>${p.nome||'Produto sem nome'}</h3><p>${p.categoria||'Sem categoria'}${p.sku?` · ${p.sku}`:''}${p.ativo===false?' · INATIVO':''}</p></div><span class="stock-badge ${low?'low':''}">${stock} em estoque</span></div><div class="product-metrics"><div><span>Custo</span><strong>${money(cost)}</strong></div><div><span>Venda</span><strong>${money(price)}</strong></div><div><span>Margem</span><strong>${margin(cost,price).toFixed(1).replace('.',',')}%</strong></div><div><span>Vendidos</span><strong>${Number(p.vendidos)||0}</strong></div></div><div class="product-actions"><button class="edit-product" data-edit="${p.id}" type="button">Editar</button><button class="toggle-product" data-toggle="${p.id}" type="button">${p.ativo===false?'Ativar':'Desativar'}</button></div></article>`}).join(''):'<div class="empty-products">Nenhuma peça encontrada.</div>';document.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>editProduct(b.dataset.edit)));document.querySelectorAll('[data-toggle]').forEach(b=>b.addEventListener('click',()=>toggleProduct(b.dataset.toggle)))}
function renderKpis(){const active=products.filter(p=>p.ativo!==false),units=active.reduce((s,p)=>s+Math.max(0,Number(p.estoque)||0),0),value=active.reduce((s,p)=>s+Math.max(0,Number(p.estoque)||0)*Math.max(0,Number(p.precoCusto)||0),0),low=active.filter(p=>(Number(p.estoque)||0)<=(Number(p.estoqueMinimo)||0)).length,start=monthStart(),month=purchases.filter(p=>{const d=dateOf(p.criadoEm);return d&&d>=start}),revenue=month.reduce((s,p)=>s+Math.max(0,Number(p.valorPago??p.valor)||0),0),profit=month.reduce((s,p)=>s+Number(p.lucroEstimado??((Number(p.valorPago??p.valor)||0)-(Number(p.custoTotal)||0))),0);$('stockValue').textContent=money(value);$('stockUnits').textContent=String(units);$('lowStock').textContent=String(low);$('monthRevenue').textContent=money(revenue);$('monthProfit').textContent=money(profit)}
function renderRankings(){const productMap=new Map(),categoryMap=new Map();for(const sale of purchases){for(const item of Array.isArray(sale.itens)?sale.itens:[]){const q=Math.max(0,Number(item.quantidade)||0),revenue=q*Math.max(0,Number(item.precoVenda)||0);const pk=item.produtoId||item.nome,prev=productMap.get(pk)||{nome:item.nome||'Produto',qtd:0,receita:0};prev.qtd+=q;prev.receita+=revenue;productMap.set(pk,prev);const ck=item.categoria||'Sem categoria',cat=categoryMap.get(ck)||{nome:ck,qtd:0,receita:0};cat.qtd+=q;cat.receita+=revenue;categoryMap.set(ck,cat)}}const top=[...productMap.values()].sort((a,b)=>b.qtd-a.qtd).slice(0,6),cats=[...categoryMap.values()].sort((a,b)=>b.qtd-a.qtd).slice(0,6);$('topProducts').innerHTML=top.length?top.map((x,i)=>`<div class="ranking-item"><div><strong>${i+1}. ${x.nome}</strong><small>${x.qtd} unidade(s) vendida(s)</small></div><strong>${money(x.receita)}</strong></div>`).join(''):'<div class="empty-products">As vendas com produtos cadastrados aparecerão aqui.</div>';$('topCategories').innerHTML=cats.length?cats.map((x,i)=>`<div class="ranking-item"><div><strong>${i+1}. ${x.nome}</strong><small>${x.qtd} unidade(s)</small></div><strong>${money(x.receita)}</strong></div>`).join(''):'<div class="empty-products">Sem categorias vendidas ainda.</div>'}
async function saveProduct(e){e.preventDefault();const id=$('productId').value.trim(),nome=$('productName').value.trim(),categoria=$('productCategory').value,sku=$('productSku').value.trim(),precoCusto=Math.max(0,parseMoney($('productCost').value)||0),precoVenda=Math.max(0,parseMoney($('productPrice').value)||0),estoque=Math.max(0,Math.floor(Number($('productStock').value)||0)),estoqueMinimo=Math.max(0,Math.floor(Number($('productMinimum').value)||0));if(!nome)return $('productStatus').textContent='Informe o nome da peça.';if(precoVenda<=0)return $('productStatus').textContent='Informe o preço de venda.';const ref=id?doc(db,'produtos',id):doc(collection(db,'produtos')),old=products.find(p=>p.id===id);await setDoc(ref,{nome,categoria,sku,precoCusto,precoVenda,estoque,estoqueMinimo,vendidos:Number(old?.vendidos)||0,ativo:old?.ativo!==false,atualizadoEm:serverTimestamp(),...(id?{}:{criadoEm:serverTimestamp()})},{merge:true});await addDoc(collection(db,'logs'),{tipo:id?'produto_editado':'produto_criado',produtoId:ref.id,nome,admin:{uid:auth.currentUser?.uid||'',email:auth.currentUser?.email||''},criadoEm:serverTimestamp()});$('productStatus').textContent='Peça salva com sucesso.';resetForm();await load()}
async function load(){const [productsSnap,purchasesSnap]=await Promise.all([getDocs(collection(db,'produtos')),getDocs(collection(db,'compras'))]);products=productsSnap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.nome||'').localeCompare(b.nome||''));purchases=purchasesSnap.docs.map(d=>({id:d.id,...d.data()}));renderKpis();renderRankings();renderProducts()}
$('productForm').addEventListener('submit',saveProduct);$('productCost').addEventListener('input',updatePreview);$('productPrice').addEventListener('input',updatePreview);$('productSearch').addEventListener('input',renderProducts);$('newProduct').addEventListener('click',()=>{resetForm();scrollTo({top:0,behavior:'smooth'})});$('cancelEdit').addEventListener('click',resetForm);updatePreview();load().catch(error=>{console.error(error);$('productsList').innerHTML='<div class="empty-products">Não foi possível carregar o estoque. Verifique as regras do Firestore.</div>'});