import { db } from './firebase.js';
import { collection,getDocs } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
import { money } from './regras-fidelidade.js';
const $=id=>document.getElementById(id);let products=[];
const num=value=>Math.max(0,Number(value)||0),margin=(cost,price)=>price>0?((price-cost)/price)*100:0,esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function sizeMap(p){if(p.estoquePorTamanho&&typeof p.estoquePorTamanho==='object')return p.estoquePorTamanho;const sizes=Array.isArray(p.tamanhos)?p.tamanhos:[],total=num(p.estoque);if(!sizes.length)return total?{'ÚNICO':total}:{};const out={};sizes.forEach((size,index)=>out[size]=index===0?total:0);return out}
function stockOf(p){const values=Object.values(sizeMap(p));return values.length?values.reduce((s,v)=>s+num(v),0):num(p.estoque)}
function sizeChips(p){const entries=Object.entries(sizeMap(p)).filter(([,qty])=>num(qty)>0);return entries.length?`<div class="size-breakdown">${entries.map(([size,qty])=>`<span><b>${esc(size)}</b>${num(qty)} un.</span>`).join('')}</div>`:'<div class="size-breakdown empty">Sem distribuição por tamanho</div>'}
function renderKpis(){const active=products.filter(p=>p.ativo!==false),units=active.reduce((s,p)=>s+stockOf(p),0),investment=active.reduce((s,p)=>s+stockOf(p)*num(p.precoCusto),0),potential=active.reduce((s,p)=>s+stockOf(p)*num(p.preco),0),profit=potential-investment,low=active.filter(p=>stockOf(p)>0&&stockOf(p)<=num(p.estoqueMinimo||3)).length,out=active.filter(p=>stockOf(p)===0).length,avg=potential>0?profit/potential*100:0;$('stockValue').textContent=money(investment);$('potentialRevenue').textContent=money(potential);$('expectedProfit').textContent=money(profit);$('stockUnits').textContent=String(units);$('productCount').textContent=String(active.length);$('lowStock').textContent=String(low);$('outOfStock').textContent=String(out);$('averageMargin').textContent=`${avg.toFixed(1).replace('.',',')}%`}
function renderProducts(){const sorted=[...products].filter(p=>p.ativo!==false).sort((a,b)=>stockOf(b)*num(b.precoCusto)-stockOf(a)*num(a.precoCusto));$('productsList').innerHTML=sorted.length?sorted.map(p=>{const stock=stockOf(p),cost=num(p.precoCusto),price=num(p.preco),investment=stock*cost,potential=stock*price,profit=potential-investment,state=stock===0?'Esgotado':stock<=num(p.estoqueMinimo||3)?'Estoque baixo':`${stock} peças`;return `<article class="dashboard-product-card"><header><div><span class="product-label">${esc(p.categoria||'Sem categoria')}</span><h3>${esc(p.nome||'Produto sem nome')}</h3><p>${esc(p.selo||'Produto padrão')}</p></div><span class="stock-badge ${stock<=num(p.estoqueMinimo||3)?'low':''}">${state}</span></header>${sizeChips(p)}<div class="product-finance"><div><span>Investido</span><strong>${money(investment)}</strong></div><div><span>Venda potencial</span><strong>${money(potential)}</strong></div><div><span>Lucro esperado</span><strong>${money(profit)}</strong></div><div><span>Margem</span><strong>${margin(cost,price).toFixed(1).replace('.',',')}%</strong></div></div></article>`}).join(''):'<div class="empty-products">Nenhuma mercadoria publicada.</div>'}
function ranking(target,list,empty){$(target).innerHTML=list.length?list.map((item,index)=>`<div class="ranking-item"><span class="rank-index">${index+1}</span><div><strong>${esc(item.nome)}</strong><small>${esc(item.detalhe)}</small></div><strong>${money(item.valor)}</strong></div>`).join(''):`<div class="empty-products">${empty}</div>`}
function renderRankings(){const active=products.filter(p=>p.ativo!==false);ranking('topInvestment',active.map(p=>({nome:p.nome||'Produto',valor:stockOf(p)*num(p.precoCusto),detalhe:`${stockOf(p)} peça(s)`})).sort((a,b)=>b.valor-a.valor).slice(0,6),'Sem investimento cadastrado.');ranking('topProfit',active.map(p=>({nome:p.nome||'Produto',valor:(num(p.preco)-num(p.precoCusto))*stockOf(p),detalhe:`Margem ${margin(num(p.precoCusto),num(p.preco)).toFixed(1).replace('.',',')}%`})).sort((a,b)=>b.valor-a.valor).slice(0,6),'Sem lucro calculado.');const cats=new Map();active.forEach(p=>{const key=p.categoria||'Sem categoria',current=cats.get(key)||{nome:key,valor:0,unidades:0};current.valor+=stockOf(p)*num(p.preco);current.unidades+=stockOf(p);cats.set(key,current)});ranking('topCategories',[...cats.values()].map(x=>({nome:x.nome,valor:x.valor,detalhe:`${x.unidades} peça(s)`})).sort((a,b)=>b.valor-a.valor).slice(0,6),'Sem categorias cadastradas.')}
async function load(){const snap=await getDocs(collection(db,'ofertas'));products=snap.docs.map(d=>({id:d.id,...d.data()})).filter(p=>p.tipo==='produto');renderKpis();renderProducts();renderRankings()}
load().catch(error=>{console.error(error);$('productsList').innerHTML='<div class="empty-products">Não foi possível carregar o Dashboard. Verifique as regras do Firestore.</div>'});