import { auth,db } from './firebase.js';
import { collection,getDocs,query,orderBy,doc,deleteDoc,updateDoc,addDoc,serverTimestamp,where,getDoc } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
import { calcularFidelidade,calcularCarteira,money } from './regras-fidelidade.js';
const $=id=>document.getElementById(id),LEVELS=['MEMBRO','BRONZE','SILVER','GOLD','PREMIUM','PLATINUM','SELECT','BLACK','ELITE','PRIME','FOUNDER'];
let rows=[];
const shortUid=v=>String(v||'').slice(-6);
const dateOf=v=>{try{return v?.toDate?v.toDate():new Date(v)}catch{return null}};
const formatDate=v=>{const d=dateOf(v);return d?d.toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'Data indisponível'};
const comprasCliente=async uid=>{const snap=await getDocs(query(collection(db,'compras'),where('clienteId','==',uid)));return snap.docs.map(d=>({id:d.id,...d.data()}))};
function filtered(){const q=$('historySearch').value.trim().toLowerCase(),period=$('historyPeriod').value,now=new Date(),week=new Date(now);week.setDate(now.getDate()-6);week.setHours(0,0,0,0);const month=new Date(now.getFullYear(),now.getMonth(),1);return rows.filter(r=>{const hay=`${r.clienteNome||''} ${r.clienteEmail||''} ${r.valor||''}`.toLowerCase(),d=dateOf(r.criadoEm);let ok=true;if(period==='today')ok=d&&d.toDateString()===now.toDateString();if(period==='week')ok=d&&d>=week;if(period==='month')ok=d&&d>=month;return (!q||hay.includes(q))&&ok})}
function render(){const list=filtered(),total=list.reduce((s,r)=>s+Math.max(0,Number(r.valor)||0),0);$('historySummary').textContent=`${list.length} venda(s) · ${money(total)} no período`;const root=$('salesHistory');root.innerHTML=list.length?list.map(r=>{const before=Math.max(0,Math.min(10,Number(r.vipAntes)||0)),after=Math.max(0,Math.min(10,Number(r.vipDepois)||0)),generated=Math.max(0,Number(r.carimbosGerados)||0),bonus=Math.max(0,Number(r.bonusGerado)||0);return `<article class="sale-card"><div><h3>${r.clienteNome||r.clienteEmail||'Cliente'}</h3><p>${r.clienteEmail||'Sem e-mail'} · ID ${shortUid(r.clienteId)}</p><small>${formatDate(r.criadoEm)}</small><div class="sale-result"><span>LV${before} ${LEVELS[before]} → LV${after} ${LEVELS[after]}</span><span>+${generated} carimbo(s)${bonus?` · +${money(bonus)} bônus`:''}</span></div></div><div class="sale-side"><div class="sale-value">${money(r.valor)}</div><button class="delete-sale" data-id="${r.id}" type="button">Excluir e estornar</button></div></article>`}).join(''):'<div class="empty-history">Nenhuma movimentação encontrada.</div>';document.querySelectorAll('.delete-sale').forEach(b=>b.addEventListener('click',()=>estornar(b.dataset.id)))}
async function load(){const snap=await getDocs(query(collection(db,'compras'),orderBy('criadoEm','desc')));rows=snap.docs.map(d=>({id:d.id,...d.data()}));render()}
async function estornar(id){const sale=rows.find(r=>r.id===id);if(!sale||!confirm(`Excluir e estornar a venda de ${money(sale.valor)}?\n\nNível, carimbos e bônus por evolução serão recalculados.`))return;const button=document.querySelector(`.delete-sale[data-id="${id}"]`);button.disabled=true;button.textContent='Recalculando...';try{await deleteDoc(doc(db,'compras',id));const remaining=await comprasCliente(sale.clienteId),total=remaining.reduce((s,p)=>s+Math.max(0,Number(p.valor)||0),0),result=calcularFidelidade(total),userRef=doc(db,'usuarios',sale.clienteId),userSnap=await getDoc(userRef);if(!userSnap.exists())throw new Error('Perfil do cliente não encontrado.');const carteira=calcularCarteira(userSnap.data(),result.vip);await updateDoc(userRef,{vip:result.vip,carimbos:result.carimbos,totalGasto:total,bonusBaseVip:carteira.bonusBaseVip,bonusManual:carteira.bonusManual,bonusNivel:carteira.bonusNivel,creditos:carteira.creditos,atualizadoEm:serverTimestamp()});await addDoc(collection(db,'logs'),{tipo:'compra_excluida_estornada',clienteId:sale.clienteId,compraId:id,valorEstornado:Number(sale.valor)||0,bonusRemovido:Math.max(0,Number(sale.bonusGerado)||0),depois:{vip:result.vip,carimbos:result.carimbos,totalGasto:total,creditos:carteira.creditos},admin:{uid:auth.currentUser?.uid||'',email:auth.currentUser?.email||''},criadoEm:serverTimestamp()});rows=rows.filter(r=>r.id!==id);render()}catch(error){console.error(error);alert('Não foi possível concluir o estorno.');button.disabled=false;button.textContent='Excluir e estornar'}}
$('historySearch').addEventListener('input',render);$('historyPeriod').addEventListener('change',render);$('refreshHistory').addEventListener('click',load);load().catch(error=>{console.error(error);$('salesHistory').innerHTML='<div class="empty-history">Não foi possível carregar o histórico.</div>'});