import { db } from './firebase.js';
import { doc,getDoc,collection,getDocs,query,where } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
import { resolverFidelidade,money } from './regras-fidelidade.js';

const levels=['MEMBRO','BRONZE','SILVER','GOLD','PREMIUM','PLATINUM','SELECT','BLACK','ELITE','PRIME','FOUNDER'];
const palettes=[
  {a:'#8c7b65',b:'#51463a',c:'#211c18',edge:'#d6c7b4',shadow:'rgba(120,105,87,.42)',text:'#fff'},
  {a:'#f0a45b',b:'#B87333',c:'#4b1f0d',edge:'#ffd0a0',shadow:'rgba(184,115,51,.48)',text:'#fff'},
  {a:'#ffffff',b:'#C0C0C0',c:'#5f6670',edge:'#ffffff',shadow:'rgba(150,160,175,.42)',text:'#15191d'},
  {a:'#ffe083',b:'#D4AF37',c:'#5b3c00',edge:'#fff2b0',shadow:'rgba(212,175,55,.52)',text:'#fff'},
  {a:'#ad82ff',b:'#6C3CE9',c:'#21104f',edge:'#e5d6ff',shadow:'rgba(108,60,233,.5)',text:'#fff'},
  {a:'#f7f8fa',b:'#c5cbd2',c:'#69737f',edge:'#ffffff',shadow:'rgba(151,164,179,.5)',text:'#11171d'},
  {a:'#4c8dff',b:'#0F52BA',c:'#031b49',edge:'#b8d4ff',shadow:'rgba(15,82,186,.52)',text:'#fff'},
  {a:'#353535',b:'#121212',c:'#000000',edge:'#d9dde3',shadow:'rgba(0,0,0,.7)',text:'#f8fafc'},
  {a:'#ee5365',b:'#B11226',c:'#3b020b',edge:'#ffc0c8',shadow:'rgba(177,18,38,.52)',text:'#fff'},
  {a:'#4265c5',b:'#1F3A93',c:'#071337',edge:'#D4AF37',shadow:'rgba(31,58,147,.58)',text:'#fff'},
  {a:'#242424',b:'#080808',c:'#000000',edge:'#FFD700',shadow:'rgba(212,175,55,.34)',text:'#fff8df'}
];
const el=id=>document.getElementById(id);
const dateText=value=>{try{const date=value?.toDate?value.toDate():new Date(value);return date.toLocaleDateString('pt-BR',{day:'2-digit',month:'short',year:'numeric'})}catch{return 'Data indisponível'}};
const loyaltyValue=purchase=>Math.max(0,Number(purchase.valorFidelidade??purchase.valorPago??purchase.valor)||0);
let lastUserId='',renderToken=0;
function applyPalette(card,vip){const palette=palettes[vip]||palettes[0];card.dataset.vip=String(vip);Object.entries({'--a':palette.a,'--b':palette.b,'--c':palette.c,'--edge':palette.edge,'--shadow':palette.shadow,'--text':palette.text}).forEach(([key,value])=>card.style.setProperty(key,value));card.classList.toggle('light-card',vip===2||vip===5);card.classList.toggle('prime-card',vip===9);card.classList.toggle('founder-card',vip===10)}
function renderHistory(items){const timeline=el('timeline');if(!timeline)return;items.sort((a,b)=>(b.criadoEm?.seconds||0)-(a.criadoEm?.seconds||0));if(!items.length){timeline.innerHTML='<div class="empty-state">Nenhuma compra registrada ainda.</div>';el('metricLastPurchase').textContent='Nenhuma';el('metricLastDate').textContent='Seu histórico aparecerá aqui';return}const latest=items[0];el('metricLastPurchase').textContent=money(latest.valor);el('metricLastDate').textContent=dateText(latest.criadoEm);timeline.innerHTML=items.slice(0,5).map(item=>`<div class="timeline-item"><span class="timeline-dot"></span><div class="timeline-main"><strong>Compra registrada</strong><span>${dateText(item.criadoEm)}</span></div><div class="timeline-value"><strong>${money(item.valor)}</strong><small>${money(loyaltyValue(item))} válido no VIP</small></div></div>`).join('')}
async function loadBenefits(vip){const next=Math.min(10,vip+1),level=el('benefitLevel'),container=el('homeBenefits');if(!level||!container)return;level.textContent=vip===10?'Benefícios Founder':`Benefícios do LV${next}`;let benefits=['Condições especiais para membros','Acesso a vantagens exclusivas'];try{const snapshot=await getDoc(doc(db,'niveis',`lv${next}`));if(snapshot.exists()&&Array.isArray(snapshot.data().beneficios)&&snapshot.data().beneficios.length)benefits=snapshot.data().beneficios}catch(error){console.error(error)}container.innerHTML=benefits.map(item=>`<div class="home-benefit">${item}</div>`).join('')}
function renderResumo(user,data,total=0,savings=0,purchases=[]){const card=el('homeCard');if(!card)return;const calc=resolverFidelidade(data,Math.max(0,Number(total)||0)),vip=calc.vip,stamps=calc.carimbos,name=data.nome||user.displayName||'Membro';applyPalette(card,vip);el('nomeUsuario').textContent=name.split(' ')[0]||'Membro';el('homeMemberTier').textContent=vip===0?'MEMBRO':`MEMBRO ${levels[vip]}`;el('homeBadge').textContent=levels[vip];el('homeClientName').textContent=name;el('homeCredits').textContent=money(data.creditos||0);el('heroLevel').textContent=`LV${vip} — ${levels[vip]}`;el('heroMessage').textContent=vip===10?'Você alcançou o nível máximo do clube.':calc.manual?'Nível ajustado pelo administrador. Continue evoluindo a partir daqui.':'Continue evoluindo para liberar novas vantagens.';el('heroStampText').textContent=`${stamps} de 10`;el('heroProgressBar').style.width=`${stamps*10}%`;el('metricCredits').textContent=money(total);el('metricSavings').textContent=money(savings);el('metricNext').textContent=vip===10?'Nível máximo':`LV${vip+1} ${levels[vip+1]}`;el('metricMissing').textContent=vip===10?'Status Founder ativo':calc.manual?`Ajuste manual ativo · faltam ${10-stamps} carimbos`:`Faltam ${money(calc.faltam)}`;renderHistory(purchases);loadBenefits(vip).catch(console.error)}
async function buscarCompras(uid){const request=getDocs(query(collection(db,'compras'),where('clienteId','==',uid))),timeout=new Promise((_,reject)=>setTimeout(()=>reject(new Error('Tempo limite ao carregar compras')),8000));const snapshot=await Promise.race([request,timeout]);return snapshot.docs.map(item=>({id:item.id,...item.data()}))}
async function renderUser(user,data){const token=++renderToken,totalSalvo=Math.max(0,Number(data.totalGasto)||0),savingsSalvo=Math.max(0,Number(data.totalEconomizado||data.creditosUsados)||0);renderResumo(user,data,totalSalvo,savingsSalvo,[]);try{const purchases=await buscarCompras(user.uid);if(token!==renderToken)return;const total=purchases.reduce((sum,purchase)=>sum+loyaltyValue(purchase),0),savings=purchases.reduce((sum,purchase)=>sum+Math.max(0,Number(purchase.creditoUsado)||0),0);renderResumo(user,data,total,savings,purchases)}catch(error){console.error('Não foi possível carregar as compras; usando resumo salvo:',error);const timeline=el('timeline');if(timeline)timeline.innerHTML='<div class="empty-state">Não foi possível atualizar o histórico agora. Os dados principais continuam disponíveis.</div>'}}
window.WDSession.subscribe(state=>{if(state.status!=='ready')return;const user=state.user,data=state.profile||{};renderResumo(user,data,Math.max(0,Number(data.totalGasto)||0),Math.max(0,Number(data.totalEconomizado||data.creditosUsados)||0),[]);if(lastUserId!==user.uid){lastUserId=user.uid;renderUser(user,data).catch(error=>console.error('Erro ao renderizar dashboard:',error))}else renderUser(user,data).catch(error=>console.error('Erro ao atualizar dashboard:',error))});
