import { db } from './firebase.js';
import { collection,getDocs } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
const grid=document.getElementById('productsGrid'),search=document.getElementById('storeSearch'),category=document.getElementById('storeCategory'),dialog=document.getElementById('productDialog'),dialogContent=document.getElementById('dialogContent');
const money=value=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let items=[];
function imagesOf(x){const list=Array.isArray(x.imagens)&&x.imagens.length?x.imagens:(x.imagem?[x.imagem]:[]);return [...new Set(list.filter(Boolean))].slice(0,4)}
function sizesOf(x){return Array.isArray(x.tamanhos)?x.tamanhos.filter(Boolean):[]}
function render(){const term=search.value.trim().toLowerCase(),cat=category.value;const filtered=items.filter(x=>x.ativo!==false&&(!cat||x.categoria===cat)&&(!term||`${x.nome} ${x.categoria} ${x.descricao}`.toLowerCase().includes(term)));grid.innerHTML=filtered.map(x=>{const images=imagesOf(x),image=images[0]?`<img src="${esc(images[0])}" alt="${esc(x.nome||'Mercadoria')}" loading="lazy" onerror="this.parentElement.classList.add('no-image');this.remove()">`:'<span>WD</span>';const old=Number(x.precoAntigo||0)>Number(x.preco||0)?`<del>${money(x.precoAntigo)}</del>`:'';const sizes=sizesOf(x);return `<article class="product-card"><button class="product-media ${images[0]?'':'no-image'}" type="button" data-open-product="${esc(x.id)}">${image}${x.selo?`<span class="product-badge">${esc(x.selo)}</span>`:''}${images.length>1?`<span class="photo-count">1/${images.length}</span>`:''}</button><div class="product-body"><span class="product-category">${esc(x.categoria||'WD Founder')}</span><h3 class="product-title">${esc(x.nome||'Mercadoria')}</h3><p class="product-description">${esc(x.descricao||'')}</p>${sizes.length?`<div class="size-preview">${sizes.slice(0,4).map(s=>`<span>${esc(s)}</span>`).join('')}</div>`:''}<div class="product-price-row"><div class="product-price">${old}<strong>${money(x.preco)}</strong></div><span class="product-stock">${Math.max(0,Number(x.estoque)||0)} em estoque</span></div><button class="product-action" type="button" data-open-product="${esc(x.id)}">${esc(x.botao||'Ver detalhes')}</button></div></article>`}).join('')||'<div class="store-empty">Nenhuma mercadoria encontrada.</div>'}
function openProduct(id){const x=items.find(item=>item.id===id);if(!x)return;const images=imagesOf(x),sizes=sizesOf(x),old=Number(x.precoAntigo||0)>Number(x.preco||0)?`<del>${money(x.precoAntigo)}</del>`:'';const gallery=images.length?`<div class="dialog-gallery">${images.map((src,i)=>`<figure><img src="${esc(src)}" alt="${esc(x.nome||'Produto')} - foto ${i+1}"></figure>`).join('')}</div><div class="gallery-dots">${images.map((_,i)=>`<span${i===0?' class="active"':''}></span>`).join('')}</div>`:'<div class="dialog-gallery no-image"><figure><span>WD</span></figure></div>';const contact=x.link?`<a class="dialog-contact" href="${esc(x.link)}" target="_blank" rel="noopener">Falar sobre este item</a>`:`<button class="dialog-contact" type="button" id="noContact">Consultar disponibilidade</button>`;dialogContent.innerHTML=`${gallery}<div class="dialog-body"><span class="product-category">${esc(x.categoria||'WD Founder')}</span><h2>${esc(x.nome||'Mercadoria')}</h2><p>${esc(x.descricao||'')}</p>${sizes.length?`<div class="dialog-sizes"><strong>Escolha o tamanho</strong><div>${sizes.map((s,i)=>`<button type="button" class="${i===0?'selected':''}">${esc(s)}</button>`).join('')}</div></div>`:''}<div class="dialog-price">${old}<strong>${money(x.preco)}</strong><span>${Math.max(0,Number(x.estoque)||0)} em estoque</span></div>${contact}</div>`;dialog.showModal();const galleryEl=dialogContent.querySelector('.dialog-gallery');const dots=[...dialogContent.querySelectorAll('.gallery-dots span')];galleryEl?.addEventListener('scroll',()=>{const width=galleryEl.clientWidth||1,index=Math.round(galleryEl.scrollLeft/width);dots.forEach((dot,i)=>dot.classList.toggle('active',i===index))},{passive:true});dialogContent.querySelectorAll('.dialog-sizes button').forEach(button=>button.addEventListener('click',()=>{dialogContent.querySelectorAll('.dialog-sizes button').forEach(b=>b.classList.remove('selected'));button.classList.add('selected')}));dialogContent.querySelector('#noContact')?.addEventListener('click',()=>alert('Este item ainda não possui WhatsApp ou link cadastrado.'))}
try{const snap=await getDocs(collection(db,'ofertas'));items=snap.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.tipo==='produto').sort((a,b)=>(Number(a.ordem)||999)-(Number(b.ordem)||999));const cats=[...new Set(items.map(x=>x.categoria).filter(Boolean))].sort();category.innerHTML='<option value="">Todas as categorias</option>'+cats.map(c=>`<option>${esc(c)}</option>`).join('');render()}catch(e){console.error(e);grid.innerHTML=`<div class="store-empty">Não foi possível carregar as mercadorias agora.<small>${esc(e.code||'')}</small></div>`}
search.addEventListener('input',render);category.addEventListener('change',render);grid.addEventListener('click',e=>{const target=e.target.closest('[data-open-product]');if(target)openProduct(target.dataset.openProduct)});document.getElementById('dialogClose').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});