import { auth,db } from './firebase.js';
import { collection,getDocs,doc,setDoc,deleteDoc,serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
const $=id=>document.getElementById(id),status=$('productStatus'),select=$('productId'),preview=$('imagePreview');
const parseMoney=v=>Number(String(v||'').replace('R$','').replace(/\./g,'').replace(',','.').trim());
let products=[],galleryImage='';
function showPreview(src=''){preview.innerHTML=src?`<img src="${src}" alt="Prévia">`:'<span>Prévia</span>'}
function clearForm(){select.value='';galleryImage='';['productName','productCategory','productBadge','productPrice','productOldPrice','productStock','productLink','productImage','productDescription'].forEach(id=>$(id).value='');$('productOrder').value=String(products.length+1);$('productButton').value='Ver item';$('productActive').checked=true;showPreview();status.textContent='Novo produto.'}
function fillForm(){const p=products.find(x=>x.id===select.value);if(!p)return clearForm();$('productName').value=p.nome||'';$('productCategory').value=p.categoria||'';$('productBadge').value=p.selo||'';$('productPrice').value=Number(p.preco||0).toFixed(2).replace('.',',');$('productOldPrice').value=p.precoAntigo?Number(p.precoAntigo).toFixed(2).replace('.',','):'';$('productStock').value=String(Number(p.estoque)||0);$('productOrder').value=String(Number(p.ordem)||1);$('productButton').value=p.botao||'Ver item';$('productLink').value=p.link||'';$('productImage').value=p.imagem&& !p.imagem.startsWith('data:')?p.imagem:'';$('productDescription').value=p.descricao||'';$('productActive').checked=p.ativo!==false;galleryImage=p.imagem?.startsWith('data:')?p.imagem:'';showPreview(p.imagem||'');status.textContent='Editando produto.'}
async function load(){try{const snap=await getDocs(collection(db,'ofertas'));products=snap.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.tipo==='produto').sort((a,b)=>(Number(a.ordem)||999)-(Number(b.ordem)||999));select.innerHTML='<option value="">Novo produto</option>'+products.map(p=>`<option value="${p.id}">${p.nome||'Produto'}</option>`).join('');fillForm()}catch(e){console.error(e);status.textContent='Não foi possível carregar as mercadorias.'}}
function compress(file){return new Promise((resolve,reject)=>{if(!file.type.startsWith('image/'))return reject(new Error('Selecione uma imagem.'));const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=900,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.72))};img.src=reader.result};reader.readAsDataURL(file)})}
$('productFile').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;status.textContent='Preparando imagem...';try{galleryImage=await compress(file);showPreview(galleryImage);status.textContent='Imagem pronta.'}catch(err){console.error(err);status.textContent='Não foi possível usar essa imagem.'}});
$('productImage').addEventListener('input',e=>{if(e.target.value.trim())showPreview(e.target.value.trim());else showPreview(galleryImage)});
async function save(){const nome=$('productName').value.trim(),preco=parseMoney($('productPrice').value),old=parseMoney($('productOldPrice').value||0);if(!nome)return status.textContent='Informe o nome.';if(!Number.isFinite(preco)||preco<0)return status.textContent='Informe um preço válido.';const id=select.value||`produto-${Date.now()}`,imagem=galleryImage||$('productImage').value.trim();const data={tipo:'produto',nome,categoria:$('productCategory').value.trim()||'WD Founder',selo:$('productBadge').value.trim(),preco,precoAntigo:Number.isFinite(old)?old:0,estoque:Math.max(0,Number($('productStock').value)||0),ordem:Math.max(1,Number($('productOrder').value)||1),botao:$('productButton').value.trim()||'Ver item',link:$('productLink').value.trim(),imagem,descricao:$('productDescription').value.trim(),ativo:$('productActive').checked,atualizadoEm:serverTimestamp(),adminUid:auth.currentUser?.uid||''};status.textContent='Salvando...';try{await setDoc(doc(db,'ofertas',id),data,{merge:true});status.textContent='Produto salvo e publicado.';await load();select.value=id;fillForm()}catch(e){console.error(e);status.textContent=`Erro ao salvar: ${e.code||e.message||'verifique as regras do Firebase'}`}}
async function remove(){const id=select.value;if(!id)return status.textContent='Selecione um produto.';if(!confirm('Excluir este produto?'))return;try{await deleteDoc(doc(db,'ofertas',id));status.textContent='Produto excluído.';await load()}catch(e){console.error(e);status.textContent='Não foi possível excluir.'}}
select.addEventListener('change',fillForm);$('newProduct').addEventListener('click',clearForm);$('saveProduct').addEventListener('click',save);$('deleteProduct').addEventListener('click',remove);load();