import { auth,db } from './firebase.js';
import { collection,getDocs,doc,setDoc,deleteDoc,serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
const $=id=>document.getElementById(id),status=$('productStatus'),select=$('productId'),preview=$('imagePreview'),thumbs=$('imageThumbs');
const parseMoney=v=>Number(String(v||'').replace('R$','').replace(/\./g,'').replace(',','.').trim());
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
let products=[],galleryImages=[];
function unique(list){return [...new Set(list.filter(Boolean))].slice(0,5)}
function margin(cost,price){return price>0?((price-cost)/price)*100:0}
function updateFinancePreview(){const cost=Math.max(0,parseMoney($('productCost').value)||0),price=Math.max(0,parseMoney($('productPrice').value)||0),old=Math.max(0,parseMoney($('productOldPrice').value)||0),stock=Math.max(0,Number($('productStock').value)||0),profit=price-cost,discount=old>price&&old>0?(1-price/old)*100:0;$('marginPreview').textContent=`Margem: ${margin(cost,price).toFixed(1).replace('.',',')}%`;$('profitPreview').textContent=`Lucro unitário: ${money(profit)}`;$('stockProfitPreview').textContent=`Lucro esperado do estoque: ${money(profit*stock)}`;$('discountPreview').textContent=`Desconto atual: ${discount.toFixed(1).replace('.',',')}%`;$('marginPreview').style.color=profit<0?'#c44747':''}
function showPreview(){const images=unique(galleryImages);preview.innerHTML=images[0]?`<img src="${images[0]}" alt="Prévia">`:'<span>Prévia</span>';thumbs.innerHTML=images.map((src,i)=>`<button type="button" data-image-index="${i}" aria-label="Remover foto ${i+1}"><img src="${src}" alt="Foto ${i+1}"><span>×</span></button>`).join('')}
function clearForm(){select.value='';galleryImages=[];['productName','productCategory','productBadge','productCost','productPrice','productOldPrice','productStock','productLink','productImage','productDescription','productSizes'].forEach(id=>$(id).value='');$('productMinimum').value='3';$('productOrder').value=String(products.length+1);$('productButton').value='Ver detalhes';$('productActive').checked=true;showPreview();updateFinancePreview();status.textContent='Novo produto.'}
function fillForm(){const p=products.find(x=>x.id===select.value);if(!p)return clearForm();$('productName').value=p.nome||'';$('productCategory').value=p.categoria||'';$('productBadge').value=p.selo||'';$('productCost').value=p.precoCusto?Number(p.precoCusto).toFixed(2).replace('.',','):'';$('productPrice').value=Number(p.preco||0).toFixed(2).replace('.',',');$('productOldPrice').value=p.precoAntigo?Number(p.precoAntigo).toFixed(2).replace('.',','):'';$('productStock').value=String(Number(p.estoque)||0);$('productMinimum').value=String(Number(p.estoqueMinimo)||3);$('productOrder').value=String(Number(p.ordem)||1);$('productButton').value=p.botao||'Ver detalhes';$('productLink').value=p.link||'';$('productSizes').value=Array.isArray(p.tamanhos)?p.tamanhos.join(', '):'';const all=Array.isArray(p.imagens)&&p.imagens.length?p.imagens:(p.imagem?[p.imagem]:[]);galleryImages=all.filter(x=>String(x).startsWith('data:'));$('productImage').value=all.filter(x=>!String(x).startsWith('data:')).join('\n');$('productDescription').value=p.descricao||'';$('productActive').checked=p.ativo!==false;showPreview();updateFinancePreview();status.textContent='Editando produto.'}
async function load(){try{const selected=select.value;const snap=await getDocs(collection(db,'ofertas'));products=snap.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.tipo==='produto').sort((a,b)=>(Number(a.ordem)||999)-(Number(b.ordem)||999));select.innerHTML='<option value="">Novo produto</option>'+products.map(p=>`<option value="${p.id}">${p.nome||'Produto'}</option>`).join('');if(products.some(p=>p.id===selected))select.value=selected;fillForm()}catch(e){console.error(e);status.textContent=`Não foi possível carregar: ${e.code||e.message||'erro desconhecido'}`}}
function compress(file){return new Promise((resolve,reject)=>{if(!file.type.startsWith('image/'))return reject(new Error('Selecione uma imagem.'));if(file.size>12*1024*1024)return reject(new Error('Imagem maior que 12 MB.'));const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=720,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.6))};img.src=reader.result};reader.readAsDataURL(file)})}
$('productFile').addEventListener('change',async e=>{const files=[...(e.target.files||[])].slice(0,Math.max(0,5-galleryImages.length));if(!files.length)return;status.textContent='Preparando fotos...';try{const result=await Promise.all(files.map(compress));galleryImages=unique([...galleryImages,...result]);showPreview();status.textContent=`${galleryImages.length} foto(s) pronta(s).`}catch(err){console.error(err);status.textContent=err.message||'Não foi possível usar uma das imagens.'}finally{e.target.value=''}});
thumbs.addEventListener('click',e=>{const button=e.target.closest('[data-image-index]');if(!button)return;galleryImages.splice(Number(button.dataset.imageIndex),1);showPreview()});
$('clearImages').addEventListener('click',()=>{galleryImages=[];$('productImage').value='';showPreview();status.textContent='Fotos removidas.'});
async function save(){const nome=$('productName').value.trim(),preco=parseMoney($('productPrice').value),old=parseMoney($('productOldPrice').value||0),cost=parseMoney($('productCost').value||0);if(!nome)return status.textContent='Informe o nome.';if(!Number.isFinite(preco)||preco<0)return status.textContent='Informe um preço válido.';if(!Number.isFinite(cost)||cost<0)return status.textContent='Informe um custo válido.';if(preco<cost&&!confirm('O preço atual está abaixo do custo e gera prejuízo. Deseja salvar mesmo assim?'))return;const id=select.value||`produto-${Date.now()}`;const urls=$('productImage').value.split(/\n+/).map(x=>x.trim()).filter(Boolean);const imagens=unique([...galleryImages,...urls]);const tamanhos=unique($('productSizes').value.split(/[,;\n]+/).map(x=>x.trim().toUpperCase()));const estoque=Math.max(0,Number($('productStock').value)||0),data={tipo:'produto',nome,categoria:$('productCategory').value.trim()||'WD Founder',selo:$('productBadge').value.trim(),preco,precoAntigo:Number.isFinite(old)?old:0,precoCusto:cost,estoque,estoqueMinimo:Math.max(0,Number($('productMinimum').value)||3),margemAtual:margin(cost,preco),lucroUnitario:preco-cost,lucroEsperadoEstoque:(preco-cost)*estoque,ordem:Math.max(1,Number($('productOrder').value)||1),botao:$('productButton').value.trim()||'Ver detalhes',link:$('productLink').value.trim(),imagem:imagens[0]||'',imagens,tamanhos,descricao:$('productDescription').value.trim(),ativo:$('productActive').checked,atualizadoEm:serverTimestamp(),adminUid:auth.currentUser?.uid||''};status.textContent='Salvando...';try{await setDoc(doc(db,'ofertas',id),data,{merge:true});status.textContent='Produto salvo, publicado e sincronizado com o dashboard.';await load();select.value=id;fillForm()}catch(e){console.error(e);status.textContent=`Erro ao salvar: ${e.code||e.message||'verifique as regras do Firebase'}`}}
async function remove(){const id=select.value;if(!id)return status.textContent='Selecione um produto.';if(!confirm('Excluir este produto?'))return;try{await deleteDoc(doc(db,'ofertas',id));status.textContent='Produto excluído.';await load()}catch(e){console.error(e);status.textContent=`Não foi possível excluir: ${e.code||e.message||'erro'}`}}
select.addEventListener('change',fillForm);$('newProduct').addEventListener('click',clearForm);$('saveProduct').addEventListener('click',save);$('deleteProduct').addEventListener('click',remove);['productCost','productPrice','productOldPrice','productStock'].forEach(id=>$(id).addEventListener('input',updateFinancePreview));updateFinancePreview();load();