import { auth,db } from './firebase.js';
import { collection,getDocs,doc,setDoc,deleteDoc,serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
const $=id=>document.getElementById(id),status=$('productStatus'),select=$('productId'),preview=$('imagePreview'),thumbs=$('imageThumbs');
const SIZES=['PP','P','M','G','GG','XG','ÚNICO'];
const CATEGORY_PRESETS=['Blusas','Calças','Acessórios','Conjuntos','Casacos','Bermudas','Vestidos','Calçados'];
const parseMoney=v=>Number(String(v||'').replace('R$','').replace(/\./g,'').replace(',','.').trim());
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
let products=[],galleryImages=[];
const unique=list=>[...new Set(list.filter(Boolean))].slice(0,5);
const margin=(cost,price)=>price>0?((price-cost)/price)*100:0;
function sizeMap(){const out={};SIZES.forEach(size=>{const check=document.querySelector(`[data-size="${size}"]`),qty=document.querySelector(`[data-size-qty="${size}"]`);if(check?.checked){out[size]=Math.max(0,Math.floor(Number(qty?.value)||0));}});return out}
function totalStock(){return Object.values(sizeMap()).reduce((sum,value)=>sum+value,0)}
function updateSizeTotal(){$('calculatedStock').textContent=`${totalStock()} peça${totalStock()===1?'':'s'}`;updateFinancePreview()}
function setSizeMap(map={}){SIZES.forEach(size=>{const check=document.querySelector(`[data-size="${size}"]`),qty=document.querySelector(`[data-size-qty="${size}"]`),value=Math.max(0,Number(map[size])||0);check.checked=Object.prototype.hasOwnProperty.call(map,size);qty.disabled=!check.checked;qty.value=String(value)});updateSizeTotal()}
function currentCategory(){return $('productCategoryPreset').value==='Outro'?$('productCategory').value.trim():$('productCategoryPreset').value}
function setCategory(value='Blusas'){if(CATEGORY_PRESETS.includes(value)){$('productCategoryPreset').value=value;$('productCategory').hidden=true;$('productCategory').value=''}else{$('productCategoryPreset').value='Outro';$('productCategory').hidden=false;$('productCategory').value=value}}
function currentBadge(){return $('productBadgePreset').value==='Outro'?$('productBadgeCustom').value.trim():$('productBadgePreset').value}
function setBadge(value=''){const presets=['','Tendência','Novo','Promoção'];if(presets.includes(value)){$('productBadgePreset').value=value;$('productBadgeCustom').hidden=true;$('productBadgeCustom').value=''}else{$('productBadgePreset').value='Outro';$('productBadgeCustom').hidden=false;$('productBadgeCustom').value=value}}
function updateFinancePreview(){const cost=Math.max(0,parseMoney($('productCost').value)||0),price=Math.max(0,parseMoney($('productPrice').value)||0),old=Math.max(0,parseMoney($('productOldPrice').value)||0),stock=totalStock(),profit=price-cost,discount=old>price&&old>0?(1-price/old)*100:0;$('marginPreview').textContent=`${margin(cost,price).toFixed(1).replace('.',',')}%`;$('profitPreview').textContent=money(profit);$('stockProfitPreview').textContent=money(profit*stock);$('discountPreview').textContent=`${discount.toFixed(1).replace('.',',')}%`;$('marginPreview').classList.toggle('is-negative',profit<0);$('profitPreview').classList.toggle('is-negative',profit<0)}
function showPreview(){const images=unique(galleryImages);preview.innerHTML=images[0]?`<img src="${images[0]}" alt="Prévia">`:'<span>Prévia</span>';thumbs.innerHTML=images.map((src,i)=>`<button type="button" data-image-index="${i}" aria-label="Remover foto ${i+1}"><img src="${src}" alt="Foto ${i+1}"><span>×</span></button>`).join('')}
function clearForm(){select.value='';galleryImages=[];['productName','productCost','productPrice','productOldPrice','productLink','productDescription'].forEach(id=>$(id).value='');setCategory('Blusas');setBadge('');setSizeMap({});$('productMinimum').value='3';$('productOrder').value=String(products.length+1);$('productButton').value='Comprar pelo WhatsApp';$('productActive').checked=true;showPreview();updateFinancePreview();status.textContent='Novo produto.'}
function legacySizes(p){if(p.estoquePorTamanho&&typeof p.estoquePorTamanho==='object')return p.estoquePorTamanho;const sizes=Array.isArray(p.tamanhos)?p.tamanhos.filter(Boolean):[];const total=Math.max(0,Number(p.estoque)||0);if(!sizes.length)return total?{'ÚNICO':total}:{};const map={};sizes.forEach((size,index)=>map[size]=index===0?total:0);return map}
function fillForm(){const p=products.find(x=>x.id===select.value);if(!p)return clearForm();$('productName').value=p.nome||'';setCategory(p.categoria||'Blusas');setBadge(p.selo||'');$('productCost').value=p.precoCusto?Number(p.precoCusto).toFixed(2).replace('.',','):'';$('productPrice').value=Number(p.preco||0).toFixed(2).replace('.',',');$('productOldPrice').value=p.precoAntigo?Number(p.precoAntigo).toFixed(2).replace('.',','):'';$('productMinimum').value=String(Number(p.estoqueMinimo)||3);$('productOrder').value=String(Number(p.ordem)||1);$('productButton').value=p.botao||'Comprar pelo WhatsApp';$('productLink').value=p.link||'';galleryImages=Array.isArray(p.imagens)&&p.imagens.length?p.imagens.filter(Boolean):(p.imagem?[p.imagem]:[]);$('productDescription').value=p.descricao||'';$('productActive').checked=p.ativo!==false;setSizeMap(legacySizes(p));showPreview();updateFinancePreview();status.textContent='Editando produto.'}
async function load(){try{const selected=select.value;const snap=await getDocs(collection(db,'ofertas'));products=snap.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.tipo==='produto').sort((a,b)=>(Number(a.ordem)||999)-(Number(b.ordem)||999));select.innerHTML='<option value="">Novo produto</option>'+products.map(p=>`<option value="${p.id}">${p.nome||'Produto'}</option>`).join('');if(products.some(p=>p.id===selected))select.value=selected;fillForm()}catch(e){console.error(e);status.textContent=`Não foi possível carregar: ${e.code||e.message||'erro desconhecido'}`}}
function compress(file){return new Promise((resolve,reject)=>{if(!file.type.startsWith('image/'))return reject(new Error('Selecione uma imagem.'));if(file.size>12*1024*1024)return reject(new Error('Imagem maior que 12 MB.'));const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=720,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.65))};img.src=reader.result};reader.readAsDataURL(file)})}
$('productFile').addEventListener('change',async e=>{const files=[...(e.target.files||[])].slice(0,Math.max(0,5-galleryImages.length));if(!files.length)return;status.textContent='Preparando fotos...';try{galleryImages=unique([...galleryImages,...await Promise.all(files.map(compress))]);showPreview();status.textContent=`${galleryImages.length} foto(s) pronta(s).`}catch(err){console.error(err);status.textContent=err.message||'Não foi possível usar uma das imagens.'}finally{e.target.value=''}});
thumbs.addEventListener('click',e=>{const button=e.target.closest('[data-image-index]');if(!button)return;galleryImages.splice(Number(button.dataset.imageIndex),1);showPreview()});
$('clearImages').addEventListener('click',()=>{galleryImages=[];showPreview();status.textContent='Fotos removidas.'});
document.querySelectorAll('[data-size]').forEach(check=>check.addEventListener('change',()=>{const qty=document.querySelector(`[data-size-qty="${check.dataset.size}"]`);qty.disabled=!check.checked;if(check.checked&&Number(qty.value)===0)qty.value='1';if(!check.checked)qty.value='0';updateSizeTotal()}));
document.querySelectorAll('[data-size-qty]').forEach(input=>input.addEventListener('input',updateSizeTotal));
$('productCategoryPreset').addEventListener('change',()=>{const custom=$('productCategory');custom.hidden=$('productCategoryPreset').value!=='Outro';if(!custom.hidden)custom.focus()});
$('productBadgePreset').addEventListener('change',()=>{$('productBadgeCustom').hidden=$('productBadgePreset').value!=='Outro';if(!$('productBadgeCustom').hidden)$('productBadgeCustom').focus()});
async function save(){const nome=$('productName').value.trim(),preco=parseMoney($('productPrice').value),old=parseMoney($('productOldPrice').value||0),cost=parseMoney($('productCost').value||0),sizes=sizeMap(),estoque=Object.values(sizes).reduce((s,v)=>s+v,0),categoria=currentCategory();if(!nome)return status.textContent='Informe o nome.';if(!categoria)return status.textContent='Selecione ou informe uma categoria.';if(!Number.isFinite(preco)||preco<0)return status.textContent='Informe um preço válido.';if(!Number.isFinite(cost)||cost<0)return status.textContent='Informe um custo válido.';if(!Object.keys(sizes).length)return status.textContent='Selecione ao menos um tamanho ou a opção Único.';if(preco<cost&&!confirm('O preço atual está abaixo do custo e gera prejuízo. Deseja salvar mesmo assim?'))return;const id=select.value||`produto-${Date.now()}`,imagens=unique(galleryImages),tamanhos=Object.keys(sizes),data={tipo:'produto',nome,categoria,selo:currentBadge(),preco,precoAntigo:Number.isFinite(old)?old:0,precoCusto:cost,estoque,estoquePorTamanho:sizes,estoqueMinimo:Math.max(0,Number($('productMinimum').value)||3),margemAtual:margin(cost,preco),lucroUnitario:preco-cost,lucroEsperadoEstoque:(preco-cost)*estoque,ordem:Math.max(1,Number($('productOrder').value)||1),botao:$('productButton').value.trim()||'Comprar pelo WhatsApp',link:$('productLink').value.trim(),imagem:imagens[0]||'',imagens,tamanhos,descricao:$('productDescription').value.trim(),ativo:$('productActive').checked,atualizadoEm:serverTimestamp(),adminUid:auth.currentUser?.uid||''};status.textContent='Salvando...';try{await setDoc(doc(db,'ofertas',id),data,{merge:true});status.textContent='Produto salvo, publicado e sincronizado com o Dashboard.';await load();select.value=id;fillForm()}catch(e){console.error(e);status.textContent=`Erro ao salvar: ${e.code||e.message||'verifique as regras do Firebase'}`}}
async function remove(){const id=select.value;if(!id)return status.textContent='Selecione um produto.';if(!confirm('Excluir este produto?'))return;try{await deleteDoc(doc(db,'ofertas',id));status.textContent='Produto excluído.';await load()}catch(e){console.error(e);status.textContent=`Não foi possível excluir: ${e.code||e.message||'erro'}`}}
select.addEventListener('change',fillForm);$('newProduct').addEventListener('click',clearForm);$('saveProduct').addEventListener('click',save);$('deleteProduct').addEventListener('click',remove);['productCost','productPrice','productOldPrice'].forEach(id=>$(id).addEventListener('input',updateFinancePreview));updateFinancePreview();load();