import { auth, db, storage } from './firebase.js';
import { updateProfile, sendPasswordResetEmail } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import { doc,setDoc,serverTimestamp,collection,getDocs,query,where } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
import { ref,uploadBytes,getDownloadURL } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-storage.js';
import { calcularFidelidade } from './regras-fidelidade.js';

const names=['MEMBRO','BRONZE','SILVER','GOLD','PREMIUM','PLATINUM','SELECT','BLACK','ELITE','PRIME','FOUNDER'];
const themes=[['#82705a','#29231d','#fff'],['#b87333','#55280f','#fff'],['#e8e8e8','#858585','#161616'],['#d4af37','#765508','#17120a'],['#8d62ef','#341477','#fff'],['#f1f2f3','#969da3','#111'],['#2471e8','#07316f','#fff'],['#333','#050505','#fff'],['#d14455','#6a0e1b','#fff'],['#3256b8','#10235d','#fff'],['#d8ad45','#76510b','#17110a']];
const form=document.getElementById('profileForm'),status=document.getElementById('profileStatus'),nomeInput=document.getElementById('nome'),telefoneInput=document.getElementById('telefone'),perfilNome=document.getElementById('perfilNome'),perfilEmail=document.getElementById('perfilEmail'),perfilNivel=document.getElementById('perfilNivel'),perfilTelefone=document.getElementById('perfilTelefone'),perfilBadge=document.getElementById('perfilBadge'),profilePage=document.querySelector('.profile-page'),avatarInitials=document.getElementById('profileAvatarInitials'),avatarImage=document.getElementById('profileAvatarImage'),photoInput=document.getElementById('profilePhotoInput'),photoButton=document.getElementById('profilePhotoButton'),resetPassword=document.getElementById('resetPassword'),darkModeToggle=document.getElementById('darkModeToggle');
let currentUser=null,currentProfile=null,formDirty=false,themeBusy=false,photoBusy=false,vipCalculado=0,lastCalculatedUid='',renderedPhoto='';
const withTimeout=(promise,ms,message)=>Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error(message)),ms))]);
function msg(texto,erro=false){if(!status)return;status.textContent=texto;status.style.color=erro?'#ff8d84':'var(--vip-a,var(--gold))'}
function iniciais(nome){return String(nome||'WD').trim().split(/\s+/).slice(0,2).map(p=>p[0]||'').join('').toUpperCase()||'WD'}
function temaLocal(uid){const value=localStorage.getItem(`wd-theme:${uid}`)||localStorage.getItem('wd-theme');return value==='dark'?'dark':value==='light'?'light':null}
function valorFidelidade(compra){return Math.max(0,Number(compra.valorFidelidade??compra.valorPago??compra.valor)||0)}
function aplicarNivel(vip){const idx=Math.max(0,Math.min(10,Number(vip)||0));perfilNivel.textContent=`LV${idx} — ${names[idx]}`;profilePage?.setAttribute('data-vip',String(idx));if(perfilBadge)perfilBadge.textContent=idx===0?'MEMBRO WD':`${names[idx]} · LV${idx}`;const box=perfilNivel.closest('.profile-field');if(!box)return;const [a,b,t]=themes[idx];box.style.background=`linear-gradient(135deg,${a},${b})`;box.style.color=t;box.style.borderColor='rgba(255,255,255,.28)';box.classList.add('level-highlight')}
async function calcularVipReal(uid){const snap=await getDocs(query(collection(db,'compras'),where('clienteId','==',uid)));const total=snap.docs.reduce((sum,item)=>sum+valorFidelidade(item.data()),0);return calcularFidelidade(total).vip}
function nivelExibido(){if(currentProfile?.ajusteManualAtivo===true)return Math.max(0,Math.min(10,Number(currentProfile.vip)||0));return Math.max(0,Math.min(10,Number(vipCalculado||currentProfile?.vip)||0))}
function showInitials(nome){if(avatarInitials){avatarInitials.textContent=iniciais(nome);avatarInitials.hidden=false}if(avatarImage)avatarImage.hidden=true}
function renderFoto(url,nome,{force=false}={}){
  const foto=String(url||'').trim();
  if(avatarInitials)avatarInitials.textContent=iniciais(nome);
  if(!avatarImage)return;
  if(!foto){renderedPhoto='';avatarImage.removeAttribute('src');showInitials(nome);return}
  if(!force&&renderedPhoto===foto&&avatarImage.complete&&avatarImage.naturalWidth>0){avatarImage.hidden=false;if(avatarInitials)avatarInitials.hidden=true;return}
  const previous=renderedPhoto;
  const nextSrc=foto.startsWith('data:')?foto:`${foto}${foto.includes('?')?'&':'?'}wdPhoto=1`;
  const probe=new Image();
  probe.decoding='async';
  probe.onload=()=>{renderedPhoto=foto;avatarImage.src=nextSrc;avatarImage.hidden=false;if(avatarInitials)avatarInitials.hidden=true};
  probe.onerror=()=>{console.warn('A foto do perfil não pôde ser carregada.');if(previous&&avatarImage.complete&&avatarImage.naturalWidth>0){avatarImage.hidden=false;if(avatarInitials)avatarInitials.hidden=true}else showInitials(nome)};
  probe.src=nextSrc;
}
function render(){if(!currentUser||!currentProfile)return;const nome=currentProfile.nome||currentUser.displayName||'Cliente Founder',telefone=currentProfile.telefone||'',tema=currentProfile.tema==='dark'||currentProfile.tema==='light'?currentProfile.tema:temaLocal(currentUser.uid)||'light',foto=currentProfile.foto||currentUser.photoURL||'';perfilNome.textContent=nome;perfilEmail.textContent=currentUser.email||currentProfile.email||'Conta autenticada';perfilTelefone.textContent=telefone||'Não informado';if(!formDirty){nomeInput.value=nome==='Cliente Founder'?'':nome;telefoneInput.value=telefone}renderFoto(foto,nome);if(!themeBusy)darkModeToggle.checked=tema==='dark';window.aplicarTemaWD?.(tema,currentUser.uid);aplicarNivel(nivelExibido())}
async function syncSession(state){if(state.status!=='ready')return;currentUser=state.user;currentProfile=state.profile||{};render();if(currentProfile.ajusteManualAtivo===true)return;if(lastCalculatedUid===currentUser.uid)return;lastCalculatedUid=currentUser.uid;try{vipCalculado=await calcularVipReal(currentUser.uid);render()}catch(error){console.error('Erro ao calcular nível real:',error);vipCalculado=Number(currentProfile.vip)||0;render()}}
window.WDSession.subscribe(state=>{syncSession(state).catch(error=>{console.error('Erro ao sincronizar perfil:',error);msg('Não foi possível sincronizar os dados da conta.',true)})});

function carregarImagem(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Não foi possível abrir esta imagem.'))};img.src=url})}
async function prepararImagem(file){if(!file?.type?.startsWith('image/'))throw new Error('Selecione uma imagem válida.');if(file.size>10*1024*1024)throw new Error('A foto deve ter no máximo 10 MB.');const img=await withTimeout(carregarImagem(file),12000,'A imagem demorou demais para abrir.');const lado=Math.min(img.naturalWidth||img.width,img.naturalHeight||img.height);if(!lado)throw new Error('A imagem não possui dimensões válidas.');const sx=((img.naturalWidth||img.width)-lado)/2,sy=((img.naturalHeight||img.height)-lado)/2,tamanho=420,canvas=document.createElement('canvas');canvas.width=tamanho;canvas.height=tamanho;const ctx=canvas.getContext('2d',{alpha:false});ctx.fillStyle='#111';ctx.fillRect(0,0,tamanho,tamanho);ctx.drawImage(img,sx,sy,lado,lado,0,0,tamanho,tamanho);const blob=await new Promise((resolve,reject)=>canvas.toBlob(result=>result?resolve(result):reject(new Error('Não foi possível processar a imagem.')),'image/jpeg',.84));const dataUrl=canvas.toDataURL('image/jpeg',.78);return {blob,dataUrl}}
async function salvarFoto(processada){const caminho=ref(storage,`usuarios/${currentUser.uid}/perfil.jpg`);try{await withTimeout(uploadBytes(caminho,processada.blob,{contentType:'image/jpeg',cacheControl:'public,max-age=300'}),20000,'O envio da foto demorou demais.');return await withTimeout(getDownloadURL(caminho),10000,'Não foi possível obter a foto enviada.')}catch(error){console.warn('Storage indisponível; usando fallback no Firestore:',error);if(processada.dataUrl.length>700000)throw new Error('A foto ficou grande demais. Tente outra imagem.');return processada.dataUrl}}
photoButton?.addEventListener('click',()=>{if(!photoBusy)photoInput?.click()});
photoInput?.addEventListener('change',async()=>{const file=photoInput.files?.[0];photoInput.value='';if(!file||!currentUser||photoBusy)return;photoBusy=true;photoButton?.classList.add('is-loading');photoButton?.setAttribute('aria-label','Enviando foto de perfil');try{msg('Preparando sua foto...');const processada=await prepararImagem(file);renderFoto(processada.dataUrl,currentProfile?.nome||currentUser.displayName,{force:true});msg('Salvando sua foto...');const foto=await salvarFoto(processada);await withTimeout(Promise.all([updateProfile(currentUser,{photoURL:foto.startsWith('data:')?null:foto}),setDoc(doc(db,'usuarios',currentUser.uid),{foto,atualizadoEm:serverTimestamp()},{merge:true})]),15000,'A foto foi processada, mas não pôde ser salva.');currentProfile={...currentProfile,foto};renderedPhoto='';renderFoto(foto,currentProfile.nome||currentUser.displayName,{force:true});document.dispatchEvent(new CustomEvent('wd-profile-photo-updated',{detail:{foto}}));msg('Foto de perfil atualizada com sucesso.')}catch(error){console.error('Erro ao atualizar foto:',error);renderFoto(currentProfile?.foto||currentUser.photoURL||'',currentProfile?.nome||currentUser.displayName,{force:true});msg(error.message||'Não foi possível atualizar a foto.',true)}finally{photoBusy=false;photoButton?.classList.remove('is-loading');photoButton?.setAttribute('aria-label','Adicionar ou alterar foto de perfil')}});

nomeInput?.addEventListener('input',()=>formDirty=true);telefoneInput?.addEventListener('input',()=>formDirty=true);
darkModeToggle?.addEventListener('change',async()=>{if(!currentUser||themeBusy)return;const tema=darkModeToggle.checked?'dark':'light',anterior=tema==='dark'?'light':'dark';themeBusy=true;darkModeToggle.disabled=true;window.aplicarTemaWD?.(tema,currentUser.uid);try{await setDoc(doc(db,'usuarios',currentUser.uid),{tema,atualizadoEm:serverTimestamp()},{merge:true});localStorage.setItem(`wd-theme:${currentUser.uid}`,tema);localStorage.setItem('wd-theme',tema);msg(tema==='dark'?'Modo noturno ativado e salvo na sua conta.':'Modo claro ativado e salvo na sua conta.')}catch(error){console.error(error);darkModeToggle.checked=anterior==='dark';window.aplicarTemaWD?.(anterior,currentUser.uid);msg('Não foi possível salvar a preferência de aparência.',true)}finally{themeBusy=false;darkModeToggle.disabled=false}});
form?.addEventListener('submit',async event=>{event.preventDefault();if(!currentUser)return;const nome=nomeInput.value.trim(),telefone=telefoneInput.value.trim();if(nome.length<2)return msg('Informe um nome válido.',true);const botao=form.querySelector('button[type="submit"]');try{botao.disabled=true;botao.textContent='Salvando...';await updateProfile(currentUser,{displayName:nome});await setDoc(doc(db,'usuarios',currentUser.uid),{nome,telefone,email:currentUser.email||'',atualizadoEm:serverTimestamp()},{merge:true});formDirty=false;msg('Dados salvos permanentemente na sua conta.')}catch(error){console.error('Erro ao salvar perfil:',error);msg('Não foi possível salvar agora.',true)}finally{botao.disabled=false;botao.textContent='Salvar alterações'}});
resetPassword?.addEventListener('click',async()=>{if(!currentUser?.email)return;try{await sendPasswordResetEmail(auth,currentUser.email);msg('Enviamos o link de alteração de senha para seu e-mail.')}catch(error){console.error(error);msg('Não foi possível enviar o link de senha.',true)}});
