import { auth, db, storage } from './firebase.js';
import { updateProfile, sendPasswordResetEmail } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import { doc,setDoc,serverTimestamp,collection,getDocs,query,where } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
import { ref,uploadBytes,getDownloadURL } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-storage.js';
import { calcularFidelidade } from './regras-fidelidade.js';

const names=['MEMBRO','BRONZE','SILVER','GOLD','PREMIUM','PLATINUM','SELECT','BLACK','ELITE','PRIME','FOUNDER'];
const themes=[['#82705a','#29231d','#fff'],['#b87333','#55280f','#fff'],['#e8e8e8','#858585','#161616'],['#d4af37','#765508','#17120a'],['#8d62ef','#341477','#fff'],['#f1f2f3','#969da3','#111'],['#2471e8','#07316f','#fff'],['#333','#050505','#fff'],['#d14455','#6a0e1b','#fff'],['#3256b8','#10235d','#fff'],['#d8ad45','#76510b','#17110a']];
const $=id=>document.getElementById(id);
const form=$('profileForm'),status=$('profileStatus'),nomeInput=$('nome'),telefoneInput=$('telefone'),perfilNome=$('perfilNome'),perfilEmail=$('perfilEmail'),perfilNivel=$('perfilNivel'),perfilTelefone=$('perfilTelefone'),perfilBadge=$('perfilBadge'),profilePage=document.querySelector('.profile-page'),avatarInitials=$('profileAvatarInitials'),avatarImage=$('profileAvatarImage'),photoInput=$('profilePhotoInput'),photoButton=$('profilePhotoButton'),resetPassword=$('resetPassword'),darkModeToggle=$('darkModeToggle');
let currentUser=null,currentProfile={},formDirty=false,themeBusy=false,photoBusy=false,vipCalculado=0,lastCalculatedUid='';
const PHOTO_KEY=uid=>`wd-profile-photo:${uid}`;
const timeout=(promise,ms,message)=>Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error(message)),ms))]);
function msg(text,error=false){if(!status)return;status.textContent=text;status.style.color=error?'#c93838':'var(--vip-a,var(--gold))'}
function initials(name){return String(name||'WD').trim().split(/\s+/).slice(0,2).map(p=>p[0]||'').join('').toUpperCase()||'WD'}
function localTheme(uid){const value=localStorage.getItem(`wd-theme:${uid}`)||localStorage.getItem('wd-theme');return value==='dark'?'dark':value==='light'?'light':null}
function purchaseValue(item){return Math.max(0,Number(item.valorFidelidade??item.valorPago??item.valor)||0)}
function officialPhoto(){if(!currentUser)return'';return String(localStorage.getItem(PHOTO_KEY(currentUser.uid))||currentProfile.foto||currentUser.photoURL||'').trim()}
function showPhoto(url,name){const source=String(url||'').trim();if(avatarInitials)avatarInitials.textContent=initials(name);if(!avatarImage)return;if(!source){avatarImage.hidden=true;avatarImage.removeAttribute('src');if(avatarInitials)avatarInitials.hidden=false;return}const probe=new Image();probe.decoding='async';probe.onload=()=>{avatarImage.src=source;avatarImage.hidden=false;if(avatarInitials)avatarInitials.hidden=true};probe.onerror=()=>{avatarImage.hidden=true;if(avatarInitials)avatarInitials.hidden=false};probe.src=source}
function applyLevel(vip){const idx=Math.max(0,Math.min(10,Number(vip)||0));perfilNivel.textContent=`LV${idx} — ${names[idx]}`;profilePage?.setAttribute('data-vip',String(idx));if(perfilBadge)perfilBadge.textContent=idx===0?'MEMBRO WD':`${names[idx]} · LV${idx}`;const box=perfilNivel.closest('.profile-field');if(box){const[a,b,t]=themes[idx];box.style.background=`linear-gradient(135deg,${a},${b})`;box.style.color=t;box.style.borderColor='rgba(255,255,255,.28)'}}
async function calculateRealVip(uid){const snap=await getDocs(query(collection(db,'compras'),where('clienteId','==',uid)));const total=snap.docs.reduce((sum,item)=>sum+purchaseValue(item.data()),0);return calcularFidelidade(total).vip}
function displayedVip(){return currentProfile?.ajusteManualAtivo===true?Math.max(0,Math.min(10,Number(currentProfile.vip)||0)):Math.max(0,Math.min(10,Number(vipCalculado||currentProfile.vip)||0))}
function render(){if(!currentUser)return;const name=currentProfile.nome||currentUser.displayName||'Cliente Founder',phone=currentProfile.telefone||'',theme=['dark','light'].includes(currentProfile.tema)?currentProfile.tema:localTheme(currentUser.uid)||'light';perfilNome.textContent=name;perfilEmail.textContent=currentUser.email||currentProfile.email||'Conta autenticada';perfilTelefone.textContent=phone||'Não informado';if(!formDirty){nomeInput.value=name==='Cliente Founder'?'':name;telefoneInput.value=phone}showPhoto(officialPhoto(),name);if(!themeBusy)darkModeToggle.checked=theme==='dark';window.aplicarTemaWD?.(theme,currentUser.uid);applyLevel(displayedVip())}
async function syncSession(state){if(state.status!=='ready')return;currentUser=state.user;currentProfile=state.profile||{};render();if(currentProfile.ajusteManualAtivo===true||lastCalculatedUid===currentUser.uid)return;lastCalculatedUid=currentUser.uid;try{vipCalculado=await calculateRealVip(currentUser.uid)}catch{vipCalculado=Number(currentProfile.vip)||0}render()}
window.WDSession.subscribe(state=>syncSession(state).catch(error=>{console.error(error);msg('Não foi possível sincronizar a conta.',true)}));

function loadImage(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),image=new Image();image.onload=()=>{URL.revokeObjectURL(url);resolve(image)};image.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Não foi possível abrir essa imagem.'))};image.src=url})}
async function preparePhoto(file){if(!file?.type?.startsWith('image/'))throw new Error('Selecione uma imagem válida.');if(file.size>10*1024*1024)throw new Error('A foto deve ter no máximo 10 MB.');const image=await timeout(loadImage(file),12000,'A imagem demorou demais para abrir.');const width=image.naturalWidth||image.width,height=image.naturalHeight||image.height,side=Math.min(width,height);if(!side)throw new Error('A imagem não possui dimensões válidas.');const canvas=document.createElement('canvas');canvas.width=512;canvas.height=512;const ctx=canvas.getContext('2d',{alpha:false});ctx.fillStyle='#111';ctx.fillRect(0,0,512,512);ctx.drawImage(image,(width-side)/2,(height-side)/2,side,side,0,0,512,512);const blob=await new Promise((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error('Não foi possível processar a imagem.')),'image/webp',.82));return{blob,preview:canvas.toDataURL('image/webp',.72)}}
async function uploadOfficialPhoto(processed){const path=ref(storage,`usuarios/${currentUser.uid}/perfil.webp`);await timeout(uploadBytes(path,processed.blob,{contentType:'image/webp',cacheControl:'public,max-age=3600'}),25000,'O envio da foto demorou demais.');return timeout(getDownloadURL(path),12000,'Não foi possível obter o endereço da foto.')}
async function persistPhoto(url){await timeout(updateProfile(currentUser,{photoURL:url}),12000,'A foto foi enviada, mas o perfil não pôde ser atualizado.');localStorage.setItem(PHOTO_KEY(currentUser.uid),url);currentProfile={...currentProfile,foto:url};try{await setDoc(doc(db,'usuarios',currentUser.uid),{foto:url,atualizadoEm:serverTimestamp()},{merge:true})}catch(error){console.warn('Espelho da foto no Firestore não autorizado:',error)}document.dispatchEvent(new CustomEvent('wd-profile-photo-updated',{detail:{foto:url,uid:currentUser.uid}}))}
function friendlyPhotoError(error){const code=String(error?.code||'');if(code.includes('storage/unauthorized'))return'Permissão de foto não publicada no Firebase Storage. Publique as regras de Storage para usuarios/{uid}/perfil.webp.';if(code.includes('storage/object-not-found'))return'O arquivo foi enviado, mas não pôde ser localizado.';if(code.includes('network'))return'Falha de conexão durante o envio da foto.';return error?.message||'Não foi possível atualizar a foto.'}
photoButton?.addEventListener('click',()=>{if(!photoBusy)photoInput?.click()});
photoInput?.addEventListener('change',async()=>{const file=photoInput.files?.[0];photoInput.value='';if(!file||!currentUser||photoBusy)return;photoBusy=true;photoButton.disabled=true;photoButton.classList.add('is-loading');const previous=officialPhoto(),name=currentProfile.nome||currentUser.displayName||'WD';try{msg('Preparando sua foto...');const processed=await preparePhoto(file);showPhoto(processed.preview,name);msg('Enviando sua foto...');const url=await uploadOfficialPhoto(processed);await persistPhoto(url);showPhoto(url,name);msg('Foto de perfil atualizada e sincronizada.')}catch(error){console.error('Erro definitivo no upload da foto:',error);showPhoto(previous,name);msg(friendlyPhotoError(error),true)}finally{photoBusy=false;photoButton.disabled=false;photoButton.classList.remove('is-loading')}});

nomeInput?.addEventListener('input',()=>formDirty=true);telefoneInput?.addEventListener('input',()=>formDirty=true);
darkModeToggle?.addEventListener('change',async()=>{if(!currentUser||themeBusy)return;const theme=darkModeToggle.checked?'dark':'light',previous=theme==='dark'?'light':'dark';themeBusy=true;darkModeToggle.disabled=true;window.aplicarTemaWD?.(theme,currentUser.uid);try{await setDoc(doc(db,'usuarios',currentUser.uid),{tema:theme,atualizadoEm:serverTimestamp()},{merge:true});localStorage.setItem(`wd-theme:${currentUser.uid}`,theme);localStorage.setItem('wd-theme',theme);msg(theme==='dark'?'Modo noturno ativado.':'Modo claro ativado.')}catch(error){darkModeToggle.checked=previous==='dark';window.aplicarTemaWD?.(previous,currentUser.uid);msg('Não foi possível salvar a aparência.',true)}finally{themeBusy=false;darkModeToggle.disabled=false}});
form?.addEventListener('submit',async event=>{event.preventDefault();if(!currentUser)return;const name=nomeInput.value.trim(),phone=telefoneInput.value.trim();if(name.length<2)return msg('Informe um nome válido.',true);const button=form.querySelector('button[type="submit"]');try{button.disabled=true;button.textContent='Salvando...';await updateProfile(currentUser,{displayName:name});await setDoc(doc(db,'usuarios',currentUser.uid),{nome:name,telefone:phone,email:currentUser.email||'',atualizadoEm:serverTimestamp()},{merge:true});currentProfile={...currentProfile,nome:name,telefone:phone};formDirty=false;render();msg('Dados salvos permanentemente.')}catch(error){console.error(error);msg('Não foi possível salvar agora.',true)}finally{button.disabled=false;button.textContent='Salvar alterações'}});
resetPassword?.addEventListener('click',async()=>{if(!currentUser?.email)return;try{await sendPasswordResetEmail(auth,currentUser.email);msg('Enviamos o link para seu e-mail.')}catch{msg('Não foi possível enviar o link de senha.',true)}});
