import { auth, db } from './firebase.js';
import { onAuthStateChanged, updateProfile, sendPasswordResetEmail } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import { doc, onSnapshot, setDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';

const names=['MEMBRO','BRONZE','SILVER','GOLD','PREMIUM','PLATINUM','SELECT','BLACK','ELITE','PRIME','FOUNDER'];
const themes=[['#82705a','#29231d','#fff'],['#b87333','#55280f','#fff'],['#e8e8e8','#858585','#161616'],['#d4af37','#765508','#17120a'],['#8d62ef','#341477','#fff'],['#f1f2f3','#969da3','#111'],['#2471e8','#07316f','#fff'],['#333','#050505','#fff'],['#d14455','#6a0e1b','#fff'],['#3256b8','#10235d','#fff'],['#d8ad45','#76510b','#17110a']];
const form=document.getElementById('profileForm'),status=document.getElementById('profileStatus'),nomeInput=document.getElementById('nome'),telefoneInput=document.getElementById('telefone'),perfilNome=document.getElementById('perfilNome'),perfilEmail=document.getElementById('perfilEmail'),perfilNivel=document.getElementById('perfilNivel'),perfilTelefone=document.getElementById('perfilTelefone'),avatar=document.querySelector('.avatar'),resetPassword=document.getElementById('resetPassword'),darkModeToggle=document.getElementById('darkModeToggle');
let currentUser=null,unsubscribeProfile=null,formDirty=false,themeBusy=false;
function msg(texto,erro=false){status.textContent=texto;status.style.color=erro?'#d56a60':'var(--gold)'}
function iniciais(nome){return String(nome||'WD').trim().split(/\s+/).slice(0,2).map(p=>p[0]||'').join('').toUpperCase()||'WD'}
function aplicarNivel(vip){const idx=Math.max(0,Math.min(10,Number(vip)||0));perfilNivel.textContent=`LV${idx} — ${names[idx]}`;const box=perfilNivel.closest('.profile-field');if(!box)return;const [a,b,t]=themes[idx];box.style.background=`linear-gradient(135deg,${a},${b})`;box.style.color=t;box.style.borderColor='rgba(255,255,255,.28)';box.classList.add('level-highlight')}
function renderProfile(user,data){const vip=Math.max(0,Math.min(10,Number(data.vip)||0)),nome=data.nome||user.displayName||'Cliente Founder',telefone=data.telefone||'',tema=data.tema==='dark'?'dark':'light';perfilNome.textContent=nome;perfilEmail.textContent=user.email||data.email||'Conta autenticada';perfilTelefone.textContent=telefone||'Não informado';if(!formDirty){nomeInput.value=nome==='Cliente Founder'?'':nome;telefoneInput.value=telefone}if(avatar)avatar.textContent=iniciais(nome);darkModeToggle.checked=tema==='dark';aplicarNivel(vip)}
nomeInput.addEventListener('input',()=>formDirty=true);telefoneInput.addEventListener('input',()=>formDirty=true);
darkModeToggle.addEventListener('change',async()=>{if(!currentUser||themeBusy)return;const tema=darkModeToggle.checked?'dark':'light';window.aplicarTemaWD?.(tema);themeBusy=true;darkModeToggle.disabled=true;try{await setDoc(doc(db,'usuarios',currentUser.uid),{tema,atualizadoEm:serverTimestamp()},{merge:true});msg(tema==='dark'?'Modo noturno ativado e salvo na sua conta.':'Modo claro ativado e salvo na sua conta.')}catch(error){console.error(error);darkModeToggle.checked=tema!=='dark';window.aplicarTemaWD?.(tema==='dark'?'light':'dark');msg('Não foi possível salvar a preferência de aparência.',true)}finally{themeBusy=false;darkModeToggle.disabled=false}});
onAuthStateChanged(auth,async user=>{if(!user){location.replace('index.html');return}currentUser=user;unsubscribeProfile?.();const ref=doc(db,'usuarios',user.uid);unsubscribeProfile=onSnapshot(ref,async snap=>{const data=snap.exists()?snap.data():{};renderProfile(user,data);if(!snap.exists()){await setDoc(ref,{nome:user.displayName||'Cliente Founder',email:user.email||'',telefone:'',role:'cliente',vip:0,carimbos:0,creditos:0,tema:'light',criadoEm:serverTimestamp(),atualizadoEm:serverTimestamp()},{merge:true})}},error=>{console.error('Erro ao acompanhar perfil:',error);msg('Não foi possível sincronizar os dados da conta.',true)})});
form.addEventListener('submit',async event=>{event.preventDefault();if(!currentUser)return;const nome=nomeInput.value.trim(),telefone=telefoneInput.value.trim();if(nome.length<2)return msg('Informe um nome válido.',true);const botao=form.querySelector('button[type="submit"]');try{botao.disabled=true;botao.textContent='Salvando...';await updateProfile(currentUser,{displayName:nome});await setDoc(doc(db,'usuarios',currentUser.uid),{nome,telefone,email:currentUser.email||'',atualizadoEm:serverTimestamp()},{merge:true});formDirty=false;msg('Dados salvos permanentemente na sua conta.')}catch(error){console.error('Erro ao salvar perfil:',error);msg('Não foi possível salvar agora. Verifique as regras do Firestore.',true)}finally{botao.disabled=false;botao.textContent='Salvar alterações'}});
resetPassword.addEventListener('click',async()=>{if(!currentUser?.email)return;try{await sendPasswordResetEmail(auth,currentUser.email);msg('Enviamos o link de alteração de senha para seu e-mail.')}catch(error){console.error(error);msg('Não foi possível enviar o link de senha.',true)}});