import {db} from './firebase.js';
import {collection,getDocs} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
const names=['MEMBRO','BRONZE','SILVER','GOLD','PREMIUM','PLATINUM','SELECT','BLACK','ELITE','PRIME','FOUNDER'];
const colors=['#82705a','#b87333','#c0c0c0','#d4af37','#8d62ef','#e5e4e2','#2471e8','#242424','#c92d42','#3256b8','#ffd700'];
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const root=document.querySelector('[data-view="rank"]'),podium=document.getElementById('rankPodium'),listEl=document.getElementById('rankList'),countdown=document.getElementById('rankCountdown'),cycleLabel=document.getElementById('rankCycleLabel');
let users=[],purchases=[],mode='spend',period='week',timer=null;
function hash(value){let h=2166136261;for(const c of String(value||'')){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function alias(uid){const a=['NOVA','ONYX','LUX','PRIME','VANTA','AURA','NEXO','ORBIT','ROYAL','ZENITH'];const n=hash(uid);return `@${a[n%a.length]}-${(n%1679616).toString(36).toUpperCase().padStart(4,'0')}`}
function dateOf(value){if(value?.toDate)return value.toDate();if(value?.seconds)return new Date(Number(value.seconds)*1000);const d=new Date(value||0);return Number.isNaN(d.getTime())?new Date(0):d}
function startOfWeek(){const d=new Date(),day=(d.getDay()+6)%7;d.setHours(0,0,0,0);d.setDate(d.getDate()-day);return d}
function startOfMonth(){const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1)}
function nextBoundary(){const d=new Date();if(period==='week'){const s=startOfWeek();s.setDate(s.getDate()+7);return s}if(period==='month')return new Date(d.getFullYear(),d.getMonth()+1,1);return new Date(d.getFullYear()+1,0,1)}
function filteredPurchases(){if(period==='all')return purchases;const start=period==='week'?startOfWeek():startOfMonth();return purchases.filter(p=>dateOf(p.criadoEm)>=start)}
function entries(){const spent=new Map();filteredPurchases().forEach(p=>{const id=String(p.clienteId||'');if(id)spent.set(id,(spent.get(id)||0)+Math.max(0,Number(p.valorFidelidade??p.valorPago??p.valor)||0))});return users.map(u=>({id:u.id,photo:String(u.foto||''),vip:Math.max(0,Math.min(10,Number(u.vip)||0)),spent:period==='all'?Math.max(Number(u.totalGasto)||0,spent.get(u.id)||0):(spent.get(u.id)||0),alias:alias(u.id)})).filter(x=>mode==='vip'||x.spent>0).sort((a,b)=>mode==='spend'?(b.spent-a.spent||b.vip-a.vip):(b.vip-a.vip||b.spent-a.spent||a.alias.localeCompare(b.alias)))}
function avatar(item){return `<div class="rank-avatar" style="--rank-accent:${colors[item.vip]}">${item.photo?`<img src="${item.photo.replace(/"/g,'&quot;')}" alt="Foto pública de ${item.alias}" onerror="this.remove();this.parentElement.querySelector('span').hidden=false">`:''}<span ${item.photo?'hidden':''}>${item.alias.slice(1,3)}</span></div>`}
function card(item,place){if(!item)return `<article class="podium-card" data-place="${place}"><span class="podium-place">${place}</span><div class="rank-avatar"><span>?</span></div><strong class="rank-alias">Vaga aberta</strong></article>`;return `<article class="podium-card" data-place="${place}" style="--rank-accent:${colors[item.vip]}"><span class="podium-place">${place}</span>${avatar(item)}<strong class="rank-alias">${item.alias}</strong><span class="rank-level">LV${item.vip} · ${names[item.vip]}</span><strong class="rank-score">${mode==='spend'?money(item.spent):`LV${item.vip}`}<small>${mode==='spend'?'TOTAL NO CICLO':money(item.spent)+' EM COMPRAS'}</small></strong></article>`}
function render(){const data=entries(),order=[data[1],data[0],data[2]];podium.innerHTML=card(order[0],2)+card(order[1],1)+card(order[2],3);listEl.innerHTML=data.slice(3,30).map((item,i)=>`<div class="rank-row" style="--rank-accent:${colors[item.vip]}"><span class="rank-position">${i+4}</span>${avatar(item)}<div class="rank-copy"><strong>${item.alias}</strong><small>LV${item.vip} · ${names[item.vip]}</small></div><strong class="rank-row-score">${mode==='spend'?money(item.spent):`LV${item.vip}`}<small>${mode==='spend'?'NO CICLO':money(item.spent)}</small></strong></div>`).join('')||'<div class="rank-loading">Ainda não há participantes suficientes neste ciclo.</div>';cycleLabel.textContent=period==='week'?'Semanal':period==='month'?'Mensal':'Geral'}
function tick(){const diff=Math.max(0,nextBoundary()-new Date()),days=Math.floor(diff/86400000),hours=Math.floor(diff/3600000)%24,mins=Math.floor(diff/60000)%60,secs=Math.floor(diff/1000)%60;countdown.textContent=period==='all'?'SEM REINÍCIO':`${days?days+'d ':''}${String(hours).padStart(2,'0')}:${String(mins).padStart(2,'0')}:${String(secs).padStart(2,'0')}`}
root?.addEventListener('click',e=>{const m=e.target.closest('[data-rank-mode]'),p=e.target.closest('[data-rank-period]');if(m){mode=m.dataset.rankMode;root.querySelectorAll('[data-rank-mode]').forEach(b=>b.classList.toggle('is-active',b===m));render()}if(p){period=p.dataset.rankPeriod;root.querySelectorAll('[data-rank-period]').forEach(b=>b.classList.toggle('is-active',b===p));render();tick()}});
(async()=>{try{const [us,ps]=await Promise.all([getDocs(collection(db,'usuarios')),getDocs(collection(db,'compras'))]);users=us.docs.map(d=>({id:d.id,...d.data()}));purchases=ps.docs.map(d=>d.data());render();tick();timer=setInterval(tick,1000)}catch(error){console.error('Falha ao carregar ranking:',error);podium.innerHTML='<div class="rank-loading">O ranking está temporariamente indisponível.</div>';listEl.innerHTML=''}})();
window.addEventListener('beforeunload',()=>clearInterval(timer),{once:true});
