import { auth, db } from './firebase.js';
import { collection,getDocs,doc,writeBatch,serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
import { calcularFidelidade,money } from './regras-fidelidade.js';

const $=id=>document.getElementById(id),select=$('quickClient'),summary=$('quickClientSummary'),valueInput=$('quickValue'),status=$('quickStatus');
let clients=[],purchases=[],submitting=false;
const parseMoney=raw=>Number(String(raw||'').replace('R$','').replace(/\./g,'').replace(',','.').trim());
const shortUid=uid=>String(uid||'').slice(-6);
const totalCliente=id=>purchases.filter(p=>p.clienteId===id).reduce((s,p)=>s+Math.max(0,Number(p.valor)||0),0);
function carimbosGerados(antes,depois){if(depois.vip===antes.vip)return Math.max(0,depois.carimbos-antes.carimbos);let total=Math.max(0,10-antes.carimbos);if(depois.vip-antes.vip>1)total+=(depois.vip-antes.vip-1)*10;return total+depois.carimbos}
function render(){const c=clients.find(x=>x.id===select.value),value=parseMoney(valueInput.value),valor=Number.isFinite(value)&&value>0?value:0;$('previewValue').textContent=money(valor);if(!c){summary.innerHTML='<div><strong>Selecione um membro</strong><span>Os dados aparecem aqui.</span></div><span class="client-level">—</span>';$('previewStamps').textContent='0';$('previewCart').textContent='0 → 0/10';$('previewCurrent').textContent='LV0 MEMBRO';$('previewAfter').textContent='LV0 MEMBRO';$('upgradeNote').classList.remove('is-visible');return}const totalAtual=totalCliente(c.id),atual=calcularFidelidade(totalAtual),depois=calcularFidelidade(totalAtual+valor),gerados=carimbosGerados(atual,depois);summary.innerHTML=`<div><strong>${c.nome||c.email||'Membro'}</strong><span>${c.email||'Sem e-mail'} · ID ${shortUid(c.id)}</span></div><span class="client-level">LV${atual.vip} ${atual.nome}</span>`;$('previewStamps').textContent=String(gerados);$('previewCart').textContent=`${atual.carimbos} → ${depois.carimbos}/10`;$('previewCurrent').textContent=`LV${atual.vip} ${atual.nome}`;$('previewAfter').textContent=`LV${depois.vip} ${depois.nome}`;const note=$('upgradeNote');if(depois.vip>atual.vip)note.textContent=`Subirá para LV${depois.vip} ${depois.nome}. Total acumulado: ${money(depois.totalGasto)}.`;else if(depois.proximo)note.textContent=`Faltarão ${money(depois.faltam)} para LV${depois.proximo.vip} ${depois.proximo.nome}.`;else note.textContent='Nível Founder mantido.';note.classList.toggle('is-visible',valor>0)}
async function loadClients(){try{const selected=select.value,[usersSnap,purchasesSnap]=await Promise.all([getDocs(collection(db,'usuarios')),getDocs(collection(db,'compras'))]);purchases=purchasesSnap.docs.map(d=>({id:d.id,...d.data()}));clients=usersSnap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.nome||a.email||'').localeCompare(b.nome||b.email||''));select.innerHTML='<option value="">Selecione um membro</option>'+clients.map(c=>{const r=calcularFidelidade(totalCliente(c.id));return `<option value="${c.id}">${c.nome||c.email||'Membro'} · LV${r.vip} ${r.nome} · ${c.email||'sem e-mail'}</option>`}).join('');if(clients.some(c=>c.id===selected))select.value=selected;render()}catch(error){console.error(error);status.textContent='Não foi possível carregar os membros.'}}
async function submit(){if(submitting)return;const c=clients.find(x=>x.id===select.value);if(!c)return status.textContent='Selecione um membro.';const value=parseMoney(valueInput.value);if(!Number.isFinite(value)||value<=0)return status.textContent='Informe um valor válido.';submitting=true;const button=$('quickSubmit'),totalAntes=totalCliente(c.id),antes=calcularFidelidade(totalAntes),depois=calcularFidelidade(totalAntes+value),purchaseRef=doc(collection(db,'compras')),logRef=doc(collection(db,'logs')),batch=writeBatch(db);button.disabled=true;button.textContent='Registrando...';status.textContent='Confirmando movimentação...';try{batch.update(doc(db,'usuarios',c.id),{vip:depois.vip,carimbos:depois.carimbos,totalGasto:depois.totalGasto,atualizadoEm:serverTimestamp()});batch.set(purchaseRef,{clienteId:c.id,clienteNome:c.nome||'',clienteEmail:c.email||'',telefone:c.telefone||'',valor:value,totalAntes,totalDepois:depois.totalGasto,carimbosGerados:carimbosGerados(antes,depois),carimbosAntes:antes.carimbos,carimbosDepois:depois.carimbos,vipAntes:antes.vip,vipDepois:depois.vip,criadoEm:serverTimestamp()});batch.set(logRef,{tipo:'compra_registrada',clienteId:c.id,clienteNome:c.nome||c.email||'',compraId:purchaseRef.id,valor:value,admin:{uid:auth.currentUser?.uid||'',email:auth.currentUser?.email||''},criadoEm:serverTimestamp()});await batch.commit();purchases.push({id:purchaseRef.id,clienteId:c.id,valor:value,vipAntes:antes.vip,vipDepois:depois.vip,carimbosAntes:antes.carimbos,carimbosDepois:depois.carimbos});status.textContent=`Venda de ${money(value)} registrada. Pronto para a próxima.`;valueInput.value='';render();valueInput.focus()}catch(error){console.error(error);status.textContent='Não foi possível registrar. Nenhum dado parcial foi salvo.'}finally{submitting=false;button.disabled=false;button.textContent='Confirmar movimentação ✓'}}
select.addEventListener('change',render);valueInput.addEventListener('input',render);$('quickSubmit').addEventListener('click',submit);loadClients();