import { auth, db } from './firebase.js';
import { collection,getDocs,doc,writeBatch,serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
import { calcularFidelidade,bonusDaEvolucao,money } from './regras-fidelidade.js';

const $=id=>document.getElementById(id),select=$('quickClient'),summary=$('quickClientSummary'),valueInput=$('quickValue'),creditInput=$('quickCredit'),status=$('quickStatus');
let clients=[],purchases=[],products=[],cart=[],submitting=false;
const parseMoney=raw=>Number(String(raw||'').replace('R$','').replace(/\./g,'').replace(',','.').trim());
const shortUid=uid=>String(uid||'').slice(-6);
const loyaltyValue=p=>Math.max(0,Number(p.valorFidelidade ?? p.valorPago ?? p.valor)||0);
const totalCliente=id=>purchases.filter(p=>p.clienteId===id).reduce((s,p)=>s+loyaltyValue(p),0);
function carimbosGerados(antes,depois){if(depois.vip===antes.vip)return Math.max(0,depois.carimbos-antes.carimbos);let total=Math.max(0,10-antes.carimbos);if(depois.vip-antes.vip>1)total+=(depois.vip-antes.vip-1)*10;return total+depois.carimbos}
function atualizarOpcao(c,resultado){const option=[...select.options].find(o=>o.value===c.id);if(option)option.textContent=`${c.nome||c.email||'Membro'} · LV${resultado.vip} ${resultado.nome} · ${c.email||'sem e-mail'}`}
function cartTotal(){return cart.reduce((s,i)=>s+i.precoVenda*i.quantidade,0)}
function cartCost(){return cart.reduce((s,i)=>s+i.precoCusto*i.quantidade,0)}
function valores(){const manual=parseMoney(valueInput.value),totalCart=cartTotal(),total=totalCart>0?totalCart:(Number.isFinite(manual)&&manual>0?manual:0),credito=parseMoney(creditInput?.value);return {total,credito:Number.isFinite(credito)&&credito>0?credito:0,totalCart}}
function renderCart(){const root=$('saleItems');if(!root)return;root.innerHTML=cart.length?cart.map((i,index)=>`<div class="sale-item"><div><strong>${i.nome}</strong><span>${i.categoria||'Produto'} · ${i.quantidade} × ${money(i.precoVenda)}</span></div><strong>${money(i.quantidade*i.precoVenda)}</strong><button type="button" data-remove="${index}">×</button></div>`).join(''):'<div class="empty-items">Nenhum item adicionado. Você ainda pode lançar um valor manual.</div>';root.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{cart.splice(Number(b.dataset.remove),1);if(cart.length)valueInput.value=cartTotal().toFixed(2).replace('.',',');else valueInput.value='';renderCart();render()}));if(cart.length){valueInput.value=cartTotal().toFixed(2).replace('.',',');valueInput.readOnly=true}else valueInput.readOnly=false}
function render(){
  const c=clients.find(x=>x.id===select.value),{total,credito}=valores();$('previewValue').textContent=money(total);
  if(!c){summary.innerHTML='<div><strong>Selecione um membro</strong><span>Os dados aparecem aqui.</span></div><span class="client-level">—</span>';$('previewStamps').textContent='0';$('previewCart').textContent='0 → 0/10';$('previewCurrent').textContent='LV0 MEMBRO';$('previewAfter').textContent='LV0 MEMBRO';$('walletBalance').textContent=money(0);$('previewCredit').textContent=money(0);$('previewPay').textContent=money(total);$('previewLoyalty').textContent=money(total);$('upgradeNote').classList.remove('is-visible');return}
  const saldo=Math.max(0,Number(c.creditos)||0),creditoUsado=Math.min(credito,total,saldo),valorPago=Math.max(0,total-creditoUsado),totalAtual=totalCliente(c.id),atual=calcularFidelidade(totalAtual),depois=calcularFidelidade(totalAtual+valorPago),gerados=carimbosGerados(atual,depois),bonus=bonusDaEvolucao(atual.vip,depois.vip);
  if(creditInput&&credito!==creditoUsado)creditInput.value=creditoUsado?creditoUsado.toFixed(2).replace('.',','):'';
  summary.innerHTML=`<div><strong>${c.nome||c.email||'Membro'}</strong><span>${c.email||'Sem e-mail'} · ID ${shortUid(c.id)}</span></div><span class="client-level">LV${atual.vip} ${atual.nome}</span>`;
  $('walletBalance').textContent=money(saldo);$('previewCredit').textContent=money(creditoUsado);$('previewPay').textContent=money(valorPago);$('previewLoyalty').textContent=money(valorPago);$('previewStamps').textContent=String(gerados);$('previewCart').textContent=`${atual.carimbos} → ${depois.carimbos}/10`;$('previewCurrent').textContent=`LV${atual.vip} ${atual.nome}`;$('previewAfter').textContent=`LV${depois.vip} ${depois.nome}`;
  const note=$('upgradeNote');if(depois.vip>atual.vip)note.textContent=`Subirá para LV${depois.vip} ${depois.nome} e receberá ${money(bonus)} de bônus.`;else if(depois.proximo)note.textContent=`Faltarão ${money(depois.faltam)} pagos para LV${depois.proximo.vip} ${depois.proximo.nome}.`;else note.textContent='Nível Founder mantido.';note.classList.toggle('is-visible',total>0)
}
async function loadData(){try{const selected=select.value,[usersSnap,purchasesSnap,productsSnap]=await Promise.all([getDocs(collection(db,'usuarios')),getDocs(collection(db,'compras')),getDocs(collection(db,'produtos'))]);purchases=purchasesSnap.docs.map(d=>({id:d.id,...d.data()}));clients=usersSnap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.nome||a.email||'').localeCompare(b.nome||b.email||''));products=productsSnap.docs.map(d=>({id:d.id,...d.data()})).filter(p=>p.ativo!==false).sort((a,b)=>(a.nome||'').localeCompare(b.nome||''));select.innerHTML='<option value="">Selecione um membro</option>'+clients.map(c=>{const r=calcularFidelidade(totalCliente(c.id));return `<option value="${c.id}">${c.nome||c.email||'Membro'} · LV${r.vip} ${r.nome} · ${c.email||'sem e-mail'}</option>`}).join('');if(clients.some(c=>c.id===selected))select.value=selected;const productSelect=$('productSelect');if(productSelect)productSelect.innerHTML='<option value="">Selecione uma peça</option>'+products.map(p=>`<option value="${p.id}">${p.nome} · ${p.categoria||'Sem categoria'} · ${money(p.precoVenda)} · estoque ${Number(p.estoque)||0}</option>`).join('');renderCart();render()}catch(error){console.error(error);status.textContent='Não foi possível carregar os dados.'}}
function addProduct(){const product=products.find(p=>p.id===$('productSelect')?.value),qty=Math.max(1,Math.floor(Number($('productQty')?.value)||1));if(!product)return status.textContent='Selecione uma peça.';const existing=cart.find(i=>i.id===product.id),current=existing?.quantidade||0,stock=Math.max(0,Number(product.estoque)||0);if(current+qty>stock)return status.textContent=`Estoque insuficiente. Disponível: ${stock}.`;if(existing)existing.quantidade+=qty;else cart.push({id:product.id,nome:product.nome||'Produto',categoria:product.categoria||'',quantidade:qty,precoVenda:Math.max(0,Number(product.precoVenda)||0),precoCusto:Math.max(0,Number(product.precoCusto)||0),estoqueAntes:stock});status.textContent='';renderCart();render()}
async function submit(){if(submitting)return;const c=clients.find(x=>x.id===select.value);if(!c)return status.textContent='Selecione um membro.';const {total,credito}=valores();if(!total)return status.textContent='Informe um valor válido.';const saldoAntes=Math.max(0,Number(c.creditos)||0),creditoUsado=Math.min(credito,total,saldoAntes);if(credito>saldoAntes)return status.textContent='O bônus usado é maior que o saldo disponível.';if(credito>total)return status.textContent='O bônus não pode ser maior que o total da compra.';
  const valorPago=Math.max(0,total-creditoUsado),valorFidelidade=valorPago,totalAntes=totalCliente(c.id),antes=calcularFidelidade(totalAntes),depois=calcularFidelidade(totalAntes+valorFidelidade),bonusGerado=bonusDaEvolucao(antes.vip,depois.vip),saldoDepois=Math.max(0,saldoAntes-creditoUsado+bonusGerado),custoTotal=cartCost(),lucroEstimado=valorPago-custoTotal;
  for(const item of cart){const p=products.find(x=>x.id===item.id);if(!p||Number(p.estoque)<item.quantidade)return status.textContent=`Estoque insuficiente para ${item.nome}. Atualize a página.`}
  submitting=true;const button=$('quickSubmit'),purchaseRef=doc(collection(db,'compras')),walletRef=doc(collection(db,'carteira_movimentos')),logRef=doc(collection(db,'logs')),batch=writeBatch(db);button.disabled=true;button.textContent='Registrando...';status.textContent='Confirmando movimentação...';
  try{batch.update(doc(db,'usuarios',c.id),{vip:depois.vip,carimbos:depois.carimbos,totalGasto:depois.totalGasto,creditos:saldoDepois,atualizadoEm:serverTimestamp()});for(const item of cart){const p=products.find(x=>x.id===item.id);batch.update(doc(db,'produtos',item.id),{estoque:Math.max(0,Number(p.estoque)-item.quantidade),vendidos:(Number(p.vendidos)||0)+item.quantidade,atualizadoEm:serverTimestamp()})}batch.set(purchaseRef,{clienteId:c.id,clienteNome:c.nome||'',clienteEmail:c.email||'',telefone:c.telefone||'',valor:total,valorBruto:total,valorPago,valorFidelidade,creditoUsado,custoTotal,lucroEstimado,itens:cart.map(i=>({produtoId:i.id,nome:i.nome,categoria:i.categoria,quantidade:i.quantidade,precoVenda:i.precoVenda,precoCusto:i.precoCusto})),saldoBonusAntes:saldoAntes,saldoBonusDepois:saldoDepois,totalAntes,totalDepois:depois.totalGasto,carimbosGerados:carimbosGerados(antes,depois),carimbosAntes:antes.carimbos,carimbosDepois:depois.carimbos,vipAntes:antes.vip,vipDepois:depois.vip,bonusGerado,criadoEm:serverTimestamp()});batch.set(walletRef,{clienteId:c.id,compraId:purchaseRef.id,tipo:'compra',creditoUsado,bonusGerado,saldoAntes,saldoDepois,descricao:`Compra de ${money(total)}`,criadoEm:serverTimestamp()});batch.set(logRef,{tipo:'compra_registrada',clienteId:c.id,clienteNome:c.nome||c.email||'',compraId:purchaseRef.id,valorTotal:total,valorPago,valorFidelidade,creditoUsado,custoTotal,lucroEstimado,admin:{uid:auth.currentUser?.uid||'',email:auth.currentUser?.email||''},criadoEm:serverTimestamp()});await batch.commit();
    purchases.push({id:purchaseRef.id,clienteId:c.id,valor:total,valorPago,valorFidelidade,creditoUsado,vipAntes:antes.vip,vipDepois:depois.vip,carimbosAntes:antes.carimbos,carimbosDepois:depois.carimbos,bonusGerado});for(const item of cart){const p=products.find(x=>x.id===item.id);if(p){p.estoque=Math.max(0,Number(p.estoque)-item.quantidade);p.vendidos=(Number(p.vendidos)||0)+item.quantidade}}Object.assign(c,{vip:depois.vip,carimbos:depois.carimbos,totalGasto:depois.totalGasto,creditos:saldoDepois});atualizarOpcao(c,depois);status.textContent=`Venda registrada: ${money(total)} em produtos · ${money(creditoUsado)} em bônus · ${money(valorPago)} recebido e válido no VIP.`;valueInput.value='';if(creditInput)creditInput.value='';cart=[];renderCart();render();valueInput.focus()}catch(error){console.error(error);status.textContent='Não foi possível registrar. Nenhum dado parcial foi salvo.'}finally{submitting=false;button.disabled=false;button.textContent='Confirmar movimentação ✓'}}
select.addEventListener('change',render);valueInput.addEventListener('input',render);creditInput?.addEventListener('input',render);$('addProduct')?.addEventListener('click',addProduct);$('useMaxCredit')?.addEventListener('click',()=>{const c=clients.find(x=>x.id===select.value),{total}=valores();if(!c||!total)return;creditInput.value=String(Math.min(total,Math.max(0,Number(c.creditos)||0))).replace('.',',');render()});$('quickSubmit').addEventListener('click',submit);loadData();