import { auth, db } from './firebase.js';
import { collection,getDocs,doc,writeBatch,serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
import { calcularFidelidade,bonusDaEvolucao,money } from './regras-fidelidade.js';

const $=id=>document.getElementById(id),select=$('quickClient'),summary=$('quickClientSummary'),valueInput=$('quickValue'),creditInput=$('quickCredit'),status=$('quickStatus');
let clients=[],purchases=[],submitting=false;
const parseMoney=raw=>Number(String(raw||'').replace('R$','').replace(/\./g,'').replace(',','.').trim());
const shortUid=uid=>String(uid||'').slice(-6);
const totalCliente=id=>purchases.filter(p=>p.clienteId===id).reduce((s,p)=>s+Math.max(0,Number(p.valor)||0),0);
function carimbosGerados(antes,depois){if(depois.vip===antes.vip)return Math.max(0,depois.carimbos-antes.carimbos);let total=Math.max(0,10-antes.carimbos);if(depois.vip-antes.vip>1)total+=(depois.vip-antes.vip-1)*10;return total+depois.carimbos}
function atualizarOpcao(c,resultado){const option=[...select.options].find(o=>o.value===c.id);if(option)option.textContent=`${c.nome||c.email||'Membro'} · LV${resultado.vip} ${resultado.nome} · ${c.email||'sem e-mail'}`}
function valores(){const total=parseMoney(valueInput.value),credito=parseMoney(creditInput?.value);return {total:Number.isFinite(total)&&total>0?total:0,credito:Number.isFinite(credito)&&credito>0?credito:0}}
function render(){
  const c=clients.find(x=>x.id===select.value),{total,credito}=valores();
  $('previewValue').textContent=money(total);
  if(!c){summary.innerHTML='<div><strong>Selecione um membro</strong><span>Os dados aparecem aqui.</span></div><span class="client-level">—</span>';$('previewStamps').textContent='0';$('previewCart').textContent='0 → 0/10';$('previewCurrent').textContent='LV0 MEMBRO';$('previewAfter').textContent='LV0 MEMBRO';$('walletBalance').textContent=money(0);$('previewCredit').textContent=money(0);$('previewPay').textContent=money(total);$('upgradeNote').classList.remove('is-visible');return}
  const saldo=Math.max(0,Number(c.creditos)||0),creditoUsado=Math.min(credito,total,saldo),totalAtual=totalCliente(c.id),atual=calcularFidelidade(totalAtual),depois=calcularFidelidade(totalAtual+total),gerados=carimbosGerados(atual,depois),bonus=bonusDaEvolucao(atual.vip,depois.vip);
  if(creditInput&&credito!==creditoUsado)creditInput.value=creditoUsado?creditoUsado.toFixed(2).replace('.',','):'';
  summary.innerHTML=`<div><strong>${c.nome||c.email||'Membro'}</strong><span>${c.email||'Sem e-mail'} · ID ${shortUid(c.id)}</span></div><span class="client-level">LV${atual.vip} ${atual.nome}</span>`;
  $('walletBalance').textContent=money(saldo);$('previewCredit').textContent=money(creditoUsado);$('previewPay').textContent=money(Math.max(0,total-creditoUsado));$('previewStamps').textContent=String(gerados);$('previewCart').textContent=`${atual.carimbos} → ${depois.carimbos}/10`;$('previewCurrent').textContent=`LV${atual.vip} ${atual.nome}`;$('previewAfter').textContent=`LV${depois.vip} ${depois.nome}`;
  const note=$('upgradeNote');if(depois.vip>atual.vip)note.textContent=`Subirá para LV${depois.vip} ${depois.nome} e receberá ${money(bonus)} de bônus.`;else if(depois.proximo)note.textContent=`Faltarão ${money(depois.faltam)} para LV${depois.proximo.vip} ${depois.proximo.nome}.`;else note.textContent='Nível Founder mantido.';note.classList.toggle('is-visible',total>0)
}
async function loadClients(){try{const selected=select.value,[usersSnap,purchasesSnap]=await Promise.all([getDocs(collection(db,'usuarios')),getDocs(collection(db,'compras'))]);purchases=purchasesSnap.docs.map(d=>({id:d.id,...d.data()}));clients=usersSnap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.nome||a.email||'').localeCompare(b.nome||b.email||''));select.innerHTML='<option value="">Selecione um membro</option>'+clients.map(c=>{const r=calcularFidelidade(totalCliente(c.id));return `<option value="${c.id}">${c.nome||c.email||'Membro'} · LV${r.vip} ${r.nome} · ${c.email||'sem e-mail'}</option>`}).join('');if(clients.some(c=>c.id===selected))select.value=selected;render()}catch(error){console.error(error);status.textContent='Não foi possível carregar os membros.'}}
async function submit(){if(submitting)return;const c=clients.find(x=>x.id===select.value);if(!c)return status.textContent='Selecione um membro.';const {total,credito}=valores();if(!total)return status.textContent='Informe um valor válido.';const saldoAntes=Math.max(0,Number(c.creditos)||0),creditoUsado=Math.min(credito,total,saldoAntes);if(credito>saldoAntes)return status.textContent='O bônus usado é maior que o saldo disponível.';if(credito>total)return status.textContent='O bônus não pode ser maior que o total da compra.';
  submitting=true;const button=$('quickSubmit'),totalAntes=totalCliente(c.id),antes=calcularFidelidade(totalAntes),depois=calcularFidelidade(totalAntes+total),bonusGerado=bonusDaEvolucao(antes.vip,depois.vip),saldoDepois=Math.max(0,saldoAntes-creditoUsado+bonusGerado),valorPago=Math.max(0,total-creditoUsado),purchaseRef=doc(collection(db,'compras')),walletRef=doc(collection(db,'carteira_movimentos')),logRef=doc(collection(db,'logs')),batch=writeBatch(db);button.disabled=true;button.textContent='Registrando...';status.textContent='Confirmando movimentação...';
  try{batch.update(doc(db,'usuarios',c.id),{vip:depois.vip,carimbos:depois.carimbos,totalGasto:depois.totalGasto,creditos:saldoDepois,atualizadoEm:serverTimestamp()});batch.set(purchaseRef,{clienteId:c.id,clienteNome:c.nome||'',clienteEmail:c.email||'',telefone:c.telefone||'',valor:total,valorPago,creditoUsado,saldoBonusAntes:saldoAntes,saldoBonusDepois:saldoDepois,totalAntes,totalDepois:depois.totalGasto,carimbosGerados:carimbosGerados(antes,depois),carimbosAntes:antes.carimbos,carimbosDepois:depois.carimbos,vipAntes:antes.vip,vipDepois:depois.vip,bonusGerado,criadoEm:serverTimestamp()});batch.set(walletRef,{clienteId:c.id,compraId:purchaseRef.id,tipo:'compra',creditoUsado,bonusGerado,saldoAntes,saldoDepois,descricao:`Compra de ${money(total)}`,criadoEm:serverTimestamp()});batch.set(logRef,{tipo:'compra_registrada',clienteId:c.id,clienteNome:c.nome||c.email||'',compraId:purchaseRef.id,valorTotal:total,valorPago,creditoUsado,bonusGerado,admin:{uid:auth.currentUser?.uid||'',email:auth.currentUser?.email||''},criadoEm:serverTimestamp()});await batch.commit();
    purchases.push({id:purchaseRef.id,clienteId:c.id,valor:total,valorPago,creditoUsado,vipAntes:antes.vip,vipDepois:depois.vip,carimbosAntes:antes.carimbos,carimbosDepois:depois.carimbos,bonusGerado});Object.assign(c,{vip:depois.vip,carimbos:depois.carimbos,totalGasto:depois.totalGasto,creditos:saldoDepois});atualizarOpcao(c,depois);status.textContent=`Venda registrada: ${money(total)} total · ${money(creditoUsado)} em bônus · ${money(valorPago)} recebido.`;valueInput.value='';if(creditInput)creditInput.value='';render();valueInput.focus()}catch(error){console.error(error);status.textContent='Não foi possível registrar. Nenhum dado parcial foi salvo.'}finally{submitting=false;button.disabled=false;button.textContent='Confirmar movimentação ✓'}}
select.addEventListener('change',render);valueInput.addEventListener('input',render);creditInput?.addEventListener('input',render);$('useMaxCredit')?.addEventListener('click',()=>{const c=clients.find(x=>x.id===select.value),{total}=valores();if(!c||!total)return;creditInput.value=String(Math.min(total,Math.max(0,Number(c.creditos)||0))).replace('.',',');render()});$('quickSubmit').addEventListener('click',submit);loadClients();