const BUILD='3.1.0';
const routes={home:{title:'Início',view:'views/home.html',modules:['./home.js','./home-commerce.js']},card:{title:'Meu cartão',view:'views/card.html',modules:['./cartao.js','./offers.js']},store:{title:'Mercadorias',view:'views/store.html',modules:['./mercadorias.js','./stock-waiting-enhancer.js','./product-focus.js']},account:{title:'Minha conta',view:'views/account.html',modules:['./perfil.js']}};
const aliases={'home.html':'home','cartao.html':'card','ofertas.html':'card','mercadorias.html':'store','perfil.html':'account'};
const content=document.getElementById('conteudo'),loader=document.getElementById('spaLoader'),views=new Map(),loading=new Map(),htmlCache=new Map(),modulePreloads=new Set();let currentRoute='',navigationId=0,loaderTimer=null,sessionReady=false;
function normalizeRoute(value){return routes[value]?value:'home'}
function routeFromUrl(url=new URL(location.href)){const query=url.searchParams.get('page');if(routes[query])return query;const file=url.pathname.split('/').pop();return aliases[file]||'home'}
function routeUrl(route){const url=new URL('app.html',location.href);url.searchParams.set('page',route);return `${url.pathname}${url.search}`}
function setLoader(show,delayed=false){clearTimeout(loaderTimer);if(!show){loader.hidden=true;return}if(delayed)loaderTimer=setTimeout(()=>loader.hidden=false,260);else loader.hidden=false}
function updateNavigation(route){document.querySelectorAll('[data-spa-route]').forEach(link=>{const active=link.dataset.spaRoute===route;link.classList.toggle('is-active',active);if(active)link.setAttribute('aria-current','page');else link.removeAttribute('aria-current')})}
function preloadModule(modulePath){const href=new URL(`${modulePath}?v=${BUILD}`,location.href).href;if(modulePreloads.has(href))return;modulePreloads.add(href);const link=document.createElement('link');link.rel='modulepreload';link.href=href;document.head.append(link)}
function preloadRouteModules(route){routes[route]?.modules.forEach(preloadModule)}
async function importModules(route){await Promise.all(routes[route].modules.map(modulePath=>import(`${modulePath}?v=${BUILD}`)))}
async function fetchViewHtml(route){if(htmlCache.has(route))return htmlCache.get(route);const response=await fetch(`${routes[route].view}?v=${BUILD}`,{cache:'force-cache'});if(!response.ok)throw new Error(`Tela não encontrada (${response.status})`);const html=await response.text();htmlCache.set(route,html);return html}
async function createView(route){if(views.has(route))return views.get(route);if(loading.has(route))return loading.get(route);const promise=(async()=>{preloadRouteModules(route);const html=await fetchViewHtml(route),section=document.createElement('section');section.className='spa-view';section.dataset.route=route;section.hidden=true;section.innerHTML=html;content.append(section);views.set(route,section);await importModules(route);section.dataset.ready='true';return section})().finally(()=>loading.delete(route));loading.set(route,promise);return promise}
function showError(route,error){console.error(`Falha ao abrir ${route}:`,error);document.getElementById('spaError')?.remove();const box=document.createElement('section');box.id='spaError';box.className='spa-error';box.innerHTML='<h2>Não foi possível abrir esta tela</h2><p>Verifique sua conexão e tente novamente.</p><button type="button">Tentar novamente</button>';box.querySelector('button').addEventListener('click',()=>{box.remove();navigate(route,{replace:true,force:true})});content.append(box)}
async function navigate(route,{push=false,replace=false,force=false}={}){if(!sessionReady)return;route=normalizeRoute(route);if(route===currentRoute&&!force)return;const id=++navigationId,alreadyPrepared=views.has(route)||htmlCache.has(route);updateNavigation(route);document.body.dataset.spaNavigating='true';setLoader(true,alreadyPrepared||views.size>0);try{const next=await createView(route);if(id!==navigationId)return;views.forEach((view,key)=>{const visible=key===route;view.hidden=!visible;view.setAttribute('aria-hidden',visible?'false':'true')});document.getElementById('spaError')?.remove();currentRoute=route;document.title=`${routes[route].title} — WD Founder`;if(push)history.pushState({route},'',routeUrl(route));else if(replace)history.replaceState({route},'',routeUrl(route));window.scrollTo(0,0);document.dispatchEvent(new CustomEvent('wd-spa-route',{detail:{route}}))}catch(error){if(id===navigationId)showError(route,error)}finally{if(id===navigationId){setLoader(false);delete document.body.dataset.spaNavigating}}}
document.addEventListener('click',event=>{const routeLink=event.target.closest('[data-spa-route]');if(routeLink){event.preventDefault();navigate(routeLink.dataset.spaRoute,{push:true});return}const link=event.target.closest('a[href]');if(!link||link.target==='_blank'||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;const url=new URL(link.href,location.href);if(url.origin!==location.origin)return;const route=aliases[url.pathname.split('/').pop()];if(route){event.preventDefault();navigate(route,{push:true})}});
document.addEventListener('pointerdown',event=>{const link=event.target.closest('[data-spa-route]');if(!link)return;const route=normalizeRoute(link.dataset.spaRoute);preloadRouteModules(route);if(!htmlCache.has(route))fetchViewHtml(route).catch(()=>{});document.querySelectorAll('[data-spa-route].is-pressed').forEach(item=>item.classList.remove('is-pressed'));link.classList.add('is-pressed')},{passive:true});
document.addEventListener('pointerup',()=>document.querySelectorAll('[data-spa-route].is-pressed').forEach(item=>item.classList.remove('is-pressed')),{passive:true});
document.addEventListener('pointercancel',()=>document.querySelectorAll('[data-spa-route].is-pressed').forEach(item=>item.classList.remove('is-pressed')),{passive:true});
window.addEventListener('popstate',event=>navigate(event.state?.route||routeFromUrl()));
document.addEventListener('wd-role-ready',event=>{const name=event.detail?.dados?.nome||event.detail?.user?.displayName||'WD',initials=String(name).trim().split(/\s+/).slice(0,2).map(part=>part[0]||'').join('').toUpperCase()||'WD';document.querySelectorAll('[data-spa-avatar]').forEach(el=>el.textContent=initials)});
function carregarEstilo(href,attr){if(document.querySelector(`link[${attr}]`))return;const link=document.createElement('link');link.rel='stylesheet';link.href=href;link.setAttribute(attr,'true');document.head.append(link)}
function ativarVisualPremium(){carregarEstilo('mobile-nav-account-premium.css?v=1.0.0','data-mobile-premium');carregarEstilo('mobile-nav-fixed.css?v=1.0.0','data-mobile-fixed');carregarEstilo('store-sale-premium.css?v=1.0.0','data-store-sale-premium');carregarEstilo('store-pagination.css?v=1.0.0','data-store-pagination');carregarEstilo('store-luxury-v2.css?v=1.0.0','data-store-luxury-v2');carregarEstilo('size-stock-public.css?v=1.0.0','data-size-stock-public');carregarEstilo('member-commerce.css?v=1.0.4','data-member-commerce');carregarEstilo('theme-coherence.css?v=1.0.0','data-theme-coherence');const icons={home:'<svg class="nav-icon-svg" viewBox="0 0 24 24" aria-hidden="true"><path d="M3.5 10.5 12 3l8.5 7.5"></path><path d="M5.5 9.5V21h13V9.5"></path><path d="M9.5 21v-6h5v6"></path></svg>',store:'<svg class="nav-icon-svg" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 8.5 12 4l7 4.5v8L12 20l-7-3.5z"></path><path d="m5 8.5 7 4 7-4"></path><path d="M12 12.5V20"></path></svg>',card:'<svg class="nav-icon-svg" viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="3"></rect><path d="M3 9h18"></path><path d="M7 15h4"></path></svg>'};Object.entries(icons).forEach(([route,svg])=>{const link=document.querySelector(`.spa-bottom-nav [data-spa-route="${route}"]`);if(!link||link.querySelector('.nav-icon-svg'))return;const first=link.querySelector('span');if(first)first.outerHTML=svg;else link.insertAdjacentHTML('afterbegin',svg)})}
ativarVisualPremium();
(async()=>{const state=await window.WDSession.ready;if(state.status!=='ready')return;sessionReady=true;document.documentElement.dataset.authState='ready';document.body.classList.add('wd-auth-ready');const initialRoute=routeFromUrl();preloadRouteModules(initialRoute);await navigate(initialRoute,{replace:true});setLoader(false)})().catch(error=>showError('home',error));