const RELEASE='wd-founder-3.44.0';
const STATIC_CACHE=`${RELEASE}-static`;
const RUNTIME_CACHE=`${RELEASE}-runtime`;
const OFFLINE_FALLBACK='index.html';
const PRECACHE=['./','./index.html','./app.html','./views/home.html','./views/account.html','./views/store.html','./views/rank.html','./views/card.html','./404.html','./manifest.webmanifest','./version.json','./mobile-pwa.css','./mobile-pwa.js','./production-hardening.css','./production-hardening.js','./admin-force-refresh.js','./admin-icons-sync.js','./system-status.js','./system-status-bootstrap.js','./firebase.js','./app-session.js','./app-shell.js','./app-updater.js','./spa.js','./home.js','./home-commerce.js','./perfil.js','./store-controller.js'];
async function precacheSafely(){const cache=await caches.open(STATIC_CACHE);await Promise.allSettled(PRECACHE.map(async url=>{try{const response=await fetch(url,{cache:'reload'});if(response.ok)await cache.put(url,response)}catch(error){console.warn('Precache ignorado:',url)}}))}
self.addEventListener('install',event=>event.waitUntil(precacheSafely().then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(key=>key.startsWith('wd-founder-')&&!key.startsWith(RELEASE)).map(key=>caches.delete(key)));await self.clients.claim()})()));
function isHtml(request,url){return request.mode==='navigate'||request.destination==='document'||url.pathname.endsWith('.html')||url.pathname.includes('/views/')}
function alwaysFresh(url){return /\/(app-updater|app-shell|app-session|spa|system-status|system-status-bootstrap|mobile-pwa)\.js$/.test(url.pathname)||url.pathname.endsWith('/mobile-pwa.css')||url.pathname.endsWith('/version.json')||url.pathname.endsWith('/sw.js')||url.pathname.endsWith('/app.html')}
async function networkFirst(request){const cache=await caches.open(RUNTIME_CACHE);try{const response=await fetch(request,{cache:'no-store'});if(response?.ok)await cache.put(request,response.clone());return response}catch(error){return(await cache.match(request))||(await caches.match(request,{ignoreSearch:true}))||(isHtml(request,new URL(request.url))?await caches.match(OFFLINE_FALLBACK):null)||Response.error()}}
async function staleWhileRevalidate(request){const cache=await caches.open(RUNTIME_CACHE);const cached=(await cache.match(request))||(await caches.match(request,{ignoreSearch:true}));const network=fetch(request,{cache:'no-cache'}).then(async response=>{if(response?.ok)await cache.put(request,response.clone());return response}).catch(()=>null);return cached||(await network)||Response.error()}
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;if(alwaysFresh(url)||isHtml(request,url)){event.respondWith(networkFirst(request));return}event.respondWith(staleWhileRevalidate(request))});
self.addEventListener('message',event=>{if(event.data?.type==='SKIP_WAITING')self.skipWaiting();if(event.data?.type==='CLEAR_OLD_CACHES')event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith('wd-founder-')&&!key.startsWith(RELEASE)).map(key=>caches.delete(key)))))});