const RELEASE='wd-founder-3.17.0';
const STATIC_CACHE=`${RELEASE}-static`,RUNTIME_CACHE=`${RELEASE}-runtime`,OFFLINE_FALLBACK='index.html';
const PRECACHE=['./','./index.html','./app.html','./views/home.html','./views/account.html','./404.html','./manifest.webmanifest','./version.json','./production-hardening.css','./production-hardening.js','./firebase.js','./app-session.js','./app-shell.js','./spa.js','./home.js','./home-commerce.js','./profile-frames.css','./profile-frames-assets.css','./account-profile-v4.css','./profile-frames.js'];
self.addEventListener('install',event=>event.waitUntil(caches.open(STATIC_CACHE).then(cache=>cache.addAll(PRECACHE)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(key=>key.startsWith('wd-founder-')&&!key.startsWith(RELEASE)).map(key=>caches.delete(key)));await self.clients.claim()})()));
function html(request,url){return request.mode==='navigate'||request.destination==='document'||url.pathname.endsWith('.html')||url.pathname.includes('/views/')}
function critical(url){return /\/(app-updater|app-shell|app-session|firebase|spa|perfil|profile-frames|rank|rank-access-gate|rank-overlay-safety|store-controller|unified-admin-shell|rank-admin|bordas-admin|production-hardening)\.js$/.test(url.pathname)||/\/(account-profile-v4|profile-frames|profile-frames-assets|production-hardening|visual-premium-391|rank-profile-final-392|theme-audit-382|theme-card-identity-383|navigation-performance-381)\.css$/.test(url.pathname)}
async function networkFirst(request){const cache=await caches.open(RUNTIME_CACHE);try{const response=await fetch(request,{cache:'no-store'});if(response?.ok)await cache.put(request,response.clone());return response}catch{return(await cache.match(request))||(await caches.match(request,{ignoreSearch:true}))||(await caches.match(OFFLINE_FALLBACK))||Response.error()}}
async function instant(request){const cache=await caches.open(RUNTIME_CACHE);const cached=(await cache.match(request))||(await caches.match(request,{ignoreSearch:true}));const network=fetch(request,{cache:'no-cache'}).then(async response=>{if(response?.ok)await cache.put(request,response.clone());return response}).catch(()=>null);return cached||(await network)||(await caches.match(OFFLINE_FALLBACK))||Response.error()}
async function stale(request){const cache=await caches.open(RUNTIME_CACHE),cached=await cache.match(request);const network=fetch(request,{cache:'no-cache'}).then(async response=>{if(response?.ok)await cache.put(request,response.clone());return response}).catch(()=>null);return cached||(await network)||Response.error()}
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;if(url.pathname.endsWith('/version.json')||url.pathname.endsWith('/sw.js')){event.respondWith(networkFirst(request));return}event.respondWith(html(request,url)||critical(url)?instant(request):stale(request))});
self.addEventListener('message',event=>{if(event.data?.type==='SKIP_WAITING')self.skipWaiting();if(event.data?.type==='CLEAR_OLD_CACHES')event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith('wd-founder-')&&!key.startsWith(RELEASE)).map(key=>caches.delete(key)))))});
